import { PROFESSIONS } from '@/lib/constantes';

export interface VilleSEO {
  slug: string;
  nom: string;
  departement: string;
}

// 100 plus grandes villes de France métropolitaine — chacune génère une
// landing /emploi-soignant/:slug listée dans public/sitemap.xml.
export const VILLES_SEO: VilleSEO[] = [
  { slug: 'paris', nom: 'Paris', departement: '75' },
  { slug: 'marseille', nom: 'Marseille', departement: '13' },
  { slug: 'lyon', nom: 'Lyon', departement: '69' },
  { slug: 'toulouse', nom: 'Toulouse', departement: '31' },
  { slug: 'nice', nom: 'Nice', departement: '06' },
  { slug: 'nantes', nom: 'Nantes', departement: '44' },
  { slug: 'montpellier', nom: 'Montpellier', departement: '34' },
  { slug: 'strasbourg', nom: 'Strasbourg', departement: '67' },
  { slug: 'bordeaux', nom: 'Bordeaux', departement: '33' },
  { slug: 'lille', nom: 'Lille', departement: '59' },
  { slug: 'rennes', nom: 'Rennes', departement: '35' },
  { slug: 'reims', nom: 'Reims', departement: '51' },
  { slug: 'saint-etienne', nom: 'Saint-Étienne', departement: '42' },
  { slug: 'toulon', nom: 'Toulon', departement: '83' },
  { slug: 'le-havre', nom: 'Le Havre', departement: '76' },
  { slug: 'grenoble', nom: 'Grenoble', departement: '38' },
  { slug: 'dijon', nom: 'Dijon', departement: '21' },
  { slug: 'angers', nom: 'Angers', departement: '49' },
  { slug: 'nimes', nom: 'Nîmes', departement: '30' },
  { slug: 'clermont-ferrand', nom: 'Clermont-Ferrand', departement: '63' },
  { slug: 'saint-denis', nom: 'Saint-Denis', departement: '93' },
  { slug: 'villeurbanne', nom: 'Villeurbanne', departement: '69' },
  { slug: 'le-mans', nom: 'Le Mans', departement: '72' },
  { slug: 'aix-en-provence', nom: 'Aix-en-Provence', departement: '13' },
  { slug: 'brest', nom: 'Brest', departement: '29' },
  { slug: 'tours', nom: 'Tours', departement: '37' },
  { slug: 'amiens', nom: 'Amiens', departement: '80' },
  { slug: 'limoges', nom: 'Limoges', departement: '87' },
  { slug: 'annecy', nom: 'Annecy', departement: '74' },
  { slug: 'boulogne-billancourt', nom: 'Boulogne-Billancourt', departement: '92' },
  { slug: 'perpignan', nom: 'Perpignan', departement: '66' },
  { slug: 'besancon', nom: 'Besançon', departement: '25' },
  { slug: 'metz', nom: 'Metz', departement: '57' },
  { slug: 'orleans', nom: 'Orléans', departement: '45' },
  { slug: 'rouen', nom: 'Rouen', departement: '76' },
  { slug: 'argenteuil', nom: 'Argenteuil', departement: '95' },
  { slug: 'mulhouse', nom: 'Mulhouse', departement: '68' },
  { slug: 'montreuil', nom: 'Montreuil', departement: '93' },
  { slug: 'caen', nom: 'Caen', departement: '14' },
  { slug: 'nancy', nom: 'Nancy', departement: '54' },
  { slug: 'tourcoing', nom: 'Tourcoing', departement: '59' },
  { slug: 'roubaix', nom: 'Roubaix', departement: '59' },
  { slug: 'nanterre', nom: 'Nanterre', departement: '92' },
  { slug: 'vitry-sur-seine', nom: 'Vitry-sur-Seine', departement: '94' },
  { slug: 'avignon', nom: 'Avignon', departement: '84' },
  { slug: 'creteil', nom: 'Créteil', departement: '94' },
  { slug: 'dunkerque', nom: 'Dunkerque', departement: '59' },
  { slug: 'poitiers', nom: 'Poitiers', departement: '86' },
  { slug: 'asnieres-sur-seine', nom: 'Asnières-sur-Seine', departement: '92' },
  { slug: 'courbevoie', nom: 'Courbevoie', departement: '92' },
  { slug: 'versailles', nom: 'Versailles', departement: '78' },
  { slug: 'colombes', nom: 'Colombes', departement: '92' },
  { slug: 'aulnay-sous-bois', nom: 'Aulnay-sous-Bois', departement: '93' },
  { slug: 'aubervilliers', nom: 'Aubervilliers', departement: '93' },
  { slug: 'rueil-malmaison', nom: 'Rueil-Malmaison', departement: '92' },
  { slug: 'pau', nom: 'Pau', departement: '64' },
  { slug: 'champigny-sur-marne', nom: 'Champigny-sur-Marne', departement: '94' },
  { slug: 'antibes', nom: 'Antibes', departement: '06' },
  { slug: 'beziers', nom: 'Béziers', departement: '34' },
  { slug: 'la-rochelle', nom: 'La Rochelle', departement: '17' },
  { slug: 'saint-maur-des-fosses', nom: 'Saint-Maur-des-Fossés', departement: '94' },
  { slug: 'cannes', nom: 'Cannes', departement: '06' },
  { slug: 'calais', nom: 'Calais', departement: '62' },
  { slug: 'saint-nazaire', nom: 'Saint-Nazaire', departement: '44' },
  { slug: 'merignac', nom: 'Mérignac', departement: '33' },
  { slug: 'drancy', nom: 'Drancy', departement: '93' },
  { slug: 'colmar', nom: 'Colmar', departement: '68' },
  { slug: 'ajaccio', nom: 'Ajaccio', departement: '2A' },
  { slug: 'bourges', nom: 'Bourges', departement: '18' },
  { slug: 'issy-les-moulineaux', nom: 'Issy-les-Moulineaux', departement: '92' },
  { slug: 'levallois-perret', nom: 'Levallois-Perret', departement: '92' },
  { slug: 'la-seyne-sur-mer', nom: 'La Seyne-sur-Mer', departement: '83' },
  { slug: 'quimper', nom: 'Quimper', departement: '29' },
  { slug: 'noisy-le-grand', nom: 'Noisy-le-Grand', departement: '93' },
  { slug: 'villeneuve-d-ascq', nom: "Villeneuve-d'Ascq", departement: '59' },
  { slug: 'neuilly-sur-seine', nom: 'Neuilly-sur-Seine', departement: '92' },
  { slug: 'valence', nom: 'Valence', departement: '26' },
  { slug: 'antony', nom: 'Antony', departement: '92' },
  { slug: 'cergy', nom: 'Cergy', departement: '95' },
  { slug: 'venissieux', nom: 'Vénissieux', departement: '69' },
  { slug: 'pessac', nom: 'Pessac', departement: '33' },
  { slug: 'troyes', nom: 'Troyes', departement: '10' },
  { slug: 'clichy', nom: 'Clichy', departement: '92' },
  { slug: 'ivry-sur-seine', nom: 'Ivry-sur-Seine', departement: '94' },
  { slug: 'chambery', nom: 'Chambéry', departement: '73' },
  { slug: 'lorient', nom: 'Lorient', departement: '56' },
  { slug: 'montauban', nom: 'Montauban', departement: '82' },
  { slug: 'sarcelles', nom: 'Sarcelles', departement: '95' },
  { slug: 'niort', nom: 'Niort', departement: '79' },
  { slug: 'villejuif', nom: 'Villejuif', departement: '94' },
  { slug: 'hyeres', nom: 'Hyères', departement: '83' },
  { slug: 'saint-quentin', nom: 'Saint-Quentin', departement: '02' },
  { slug: 'beauvais', nom: 'Beauvais', departement: '60' },
  { slug: 'cholet', nom: 'Cholet', departement: '49' },
  { slug: 'vannes', nom: 'Vannes', departement: '56' },
  { slug: 'la-roche-sur-yon', nom: 'La Roche-sur-Yon', departement: '85' },
  { slug: 'bayonne', nom: 'Bayonne', departement: '64' },
  { slug: 'angouleme', nom: 'Angoulême', departement: '16' },
  { slug: 'laval', nom: 'Laval', departement: '53' },
  { slug: 'evry-courcouronnes', nom: 'Évry-Courcouronnes', departement: '91' },
];

export interface ProfessionSEO {
  valeur: string;
  label: string;
  slug: string;
  description: string;
  salaire_moyen: string;
}

export const PROFESSIONS_SEO: ProfessionSEO[] = [
  {
    valeur: 'IDE',
    label: "Infirmier(ère) Diplômé(e) d'État (IDE)",
    slug: 'infirmier-ide',
    description: "L'infirmier(ère) diplômé(e) d'État réalise des soins techniques et relationnels auprès des patients. Profession la plus demandée en intérim de santé.",
    salaire_moyen: '25-35\u20AC/h',
  },
  {
    valeur: 'AS',
    label: 'Aide-Soignant(e) (AS)',
    slug: 'aide-soignant',
    description: "L'aide-soignant(e) accompagne les patients dans les gestes de la vie quotidienne et assiste l'infirmier(ère) dans les soins d'hygiène.",
    salaire_moyen: '16-22\u20AC/h',
  },
  {
    valeur: 'AES',
    label: 'Accompagnant Éducatif et Social (AES)',
    slug: 'accompagnant-educatif-social',
    description: "L'AES intervient auprès de personnes en situation de handicap ou de dépendance pour favoriser leur autonomie et leur inclusion sociale.",
    salaire_moyen: '15-20\u20AC/h',
  },
  {
    valeur: 'IBODE',
    label: 'Infirmier(ère) de Bloc Opératoire (IBODE)',
    slug: 'infirmier-bloc-operatoire',
    description: "L'IBODE assiste le chirurgien au bloc opératoire en assurant l'instrumentation, la circulation et la gestion du matériel stérile.",
    salaire_moyen: '30-42\u20AC/h',
  },
  {
    valeur: 'IADE',
    label: 'Infirmier(ère) Anesthésiste (IADE)',
    slug: 'infirmier-anesthesiste',
    description: "L'IADE pratique l'anesthésie sous la responsabilité du médecin anesthésiste-réanimateur. Spécialisation très recherchée en intérim.",
    salaire_moyen: '32-48\u20AC/h',
  },
  {
    valeur: 'SAGE_FEMME',
    label: 'Sage-Femme',
    slug: 'sage-femme',
    description: 'La sage-femme accompagne les femmes pendant la grossesse, l\'accouchement et le post-partum. Elle assure également le suivi gynécologique.',
    salaire_moyen: '28-40\u20AC/h',
  },
  {
    valeur: 'KINE',
    label: 'Kinésithérapeute',
    slug: 'kinesitherapeute',
    description: 'Le kinésithérapeute rééduque les patients par le mouvement et les techniques manuelles. Forte demande en EHPAD et en établissements SSR.',
    salaire_moyen: '28-38\u20AC/h',
  },
  {
    valeur: 'MEDECIN',
    label: 'Médecin',
    slug: 'medecin',
    description: 'Le médecin diagnostique et traite les pathologies des patients. Les remplacements concernent la médecine générale et les spécialités hospitalières.',
    salaire_moyen: '50-80\u20AC/h',
  },
  {
    valeur: 'PHARMACIEN',
    label: 'Pharmacien(ne)',
    slug: 'pharmacien',
    description: 'Jolene propose des missions salariées de pharmacien en établissement, notamment en pharmacie à usage intérieur (PUI). Le remplacement d’un titulaire d’officine n’est pas proposé.',
    salaire_moyen: '30-45\u20AC/h',
  },
  {
    valeur: 'MANIPULATEUR_RADIO',
    label: 'Manipulateur Radio',
    slug: 'manipulateur-radio',
    description: 'Le manipulateur en électroradiologie réalise les examens d\'imagerie médicale sous la responsabilité du radiologue. Ces missions sont proposées exclusivement en contrat salarié.',
    salaire_moyen: '25-35\u20AC/h',
  },
  {
    valeur: 'PREPARATEUR_PHARMA',
    label: 'Préparateur en Pharmacie',
    slug: 'preparateur-pharmacie',
    description: 'Le préparateur en pharmacie seconde le pharmacien dans la délivrance des médicaments et la gestion des stocks.',
    salaire_moyen: '16-22\u20AC/h',
  },
  {
    valeur: 'DIETETICIEN',
    label: 'Diététicien(ne)',
    slug: 'dieteticien',
    description: 'Le diététicien élabore des programmes nutritionnels adaptés aux patients hospitalisés et accompagne la prise en charge nutritionnelle.',
    salaire_moyen: '20-28\u20AC/h',
  },
  {
    valeur: 'ERGOTHERAPEUTE',
    label: 'Ergothérapeute',
    slug: 'ergotherapeute',
    description: 'L\'ergothérapeute aide les patients à retrouver leur autonomie dans les activités quotidiennes grâce à des techniques de rééducation et d\'adaptation.',
    salaire_moyen: '24-32\u20AC/h',
  },
  {
    valeur: 'PSYCHOMOTRICIEN',
    label: 'Psychomotricien(ne)',
    slug: 'psychomotricien',
    description: 'Le psychomotricien intervient sur les troubles psychomoteurs par des techniques de relaxation, de stimulation sensorielle et de médiation corporelle.',
    salaire_moyen: '22-30\u20AC/h',
  },
  {
    valeur: 'ORTHOPHONISTE',
    label: 'Orthophoniste',
    slug: 'orthophoniste',
    description: 'L\'orthophoniste prévient, évalue et traite les troubles de la communication orale et écrite, ainsi que les troubles de la déglutition.',
    salaire_moyen: '26-36\u20AC/h',
  },
];

export function getVilleBySlug(slug: string): VilleSEO | undefined {
  return VILLES_SEO.find(v => v.slug === slug);
}

export function getProfessionBySlug(slug: string): ProfessionSEO | undefined {
  return PROFESSIONS_SEO.find(p => p.slug === slug);
}
