project_id = "flripxtsyegjshnhzjkz"

[functions.set-user-claims]
verify_jwt = false

[functions.create-invoice-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.verify-rpps]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.register-etablissement]
verify_jwt = false
