-- ============================================================
-- Enums prod Jolene (pg_type/pg_enum) — extrait le 2026-07-03
-- ============================================================

CREATE TYPE canal_notification AS ENUM ('EMAIL', 'SMS', 'PUSH', 'IN_APP');
CREATE TYPE categorie_litige AS ENUM ('PRESENCE', 'FINANCIER', 'CONDITIONS', 'COMPORTEMENT', 'AUTRE');
CREATE TYPE credit_etab_motif AS ENUM ('PARRAINAGE');
CREATE TYPE filtre_audience AS ENUM ('SOIGNANT_RECHERCHE_MISSIONS', 'ETAB_RECHERCHE_SOIGNANTS');
CREATE TYPE filtre_frequence_alerte AS ENUM ('IMMEDIATE', 'QUOTIDIENNE', 'HEBDOMADAIRE');
CREATE TYPE mode_remboursement_avoir AS ENUM ('N_A', 'AUTO_STRIPE', 'VIREMENT_MANUEL');
CREATE TYPE niveau_prevoyance_souhaite AS ENUM ('BRONZE', 'ARGENT', 'OR', 'INDIFFERENT');
CREATE TYPE niveau_qualitatif AS ENUM ('BRONZE', 'ARGENT', 'OR', 'PLATINE');
CREATE TYPE parrainage_etab_statut AS ENUM ('PENDING', 'VALIDATED', 'EXPIRED');
CREATE TYPE presence_status_enum AS ENUM ('ONLINE', 'AWAY', 'OFFLINE');
CREATE TYPE sens_notation AS ENUM ('ETAB_VERS_SOIGNANT', 'SOIGNANT_VERS_ETAB');
CREATE TYPE serie_email_statut AS ENUM ('PLANIFIE', 'ENVOYE', 'SKIPPED', 'ERREUR');
CREATE TYPE serie_onboarding_etape AS ENUM ('J0', 'J1', 'J3', 'J7');
CREATE TYPE serie_onboarding_type AS ENUM ('SOIGNANT_ONBOARDING', 'ETAB_ONBOARDING');
CREATE TYPE statut_compte_soignant AS ENUM ('ACTIF', 'SUSPENDU', 'SUPPRIME', 'EN_REVISION_ADMIN');
CREATE TYPE statut_litige_facture AS ENUM ('NORMAL', 'EN_ATTENTE_LITIGE', 'LITIGE_RESOLU_AJUSTE', 'LITIGE_RESOLU_CONFIRME');
CREATE TYPE statut_mission AS ENUM ('OUVERTE', 'ASSIGNEE', 'EN_COURS', 'TERMINEE', 'ANNULEE_PAR_ETABLISSEMENT', 'ANNULEE_PAR_SOIGNANT', 'ABSENCE', 'LITIGE', 'EXPIREE');
CREATE TYPE statut_verification AS ENUM ('EN_ATTENTE', 'VERIFIE', 'REJETE', 'EXPIRE', 'REVUE_MANUELLE_REQUISE', 'API_INDISPONIBLE');
CREATE TYPE strategie_facturation AS ENUM ('FINALE_UNIQUE', 'HEBDO_ET_FINALE');
CREATE TYPE swipe_direction AS ENUM ('LIKE', 'DISLIKE', 'SUPER_LIKE', 'FAVORI');
CREATE TYPE type_contrat AS ENUM ('CDD', 'VACATION', 'LIBERAL', 'SALARIE');
CREATE TYPE type_contrat_applique_enum AS ENUM ('LIBERAL', 'SALARIE');
CREATE TYPE type_document AS ENUM ('CARTE_IDENTITE', 'PASSEPORT', 'TITRE_SEJOUR', 'DIPLOME', 'RPPS_ADELI', 'RCP_ASSURANCE', 'VACCINATIONS', 'CASIER_JUDICIAIRE', 'RIB', 'KBIS', 'ATTESTATION_URSSAF', 'AUTORISATION_EXERCICE', 'MEDECINE_TRAVAIL', 'FORMATION_OBLIGATOIRE', 'AUTRE', 'CARTE_ORDRE', 'ATTESTATION_CPAM', 'NOTE_HONORAIRES', 'ATTESTATION_3200H', 'ARRET_MALADIE', 'ATTESTATION_SCOLARITE', 'LICENCE_REMPLACEMENT');
CREATE TYPE type_document_facture AS ENUM ('FACTURE', 'AVOIR');
CREATE TYPE type_etablissement AS ENUM ('HOPITAL_PUBLIC', 'CLINIQUE_PRIVEE', 'EHPAD', 'SSIAD', 'HAD', 'CENTRE_SANTE', 'LABO', 'IME', 'MAS', 'FAM', 'PHARMACIE_OFFICINE', 'ESPIC', 'CABINET_MEDICAL', 'CABINET_DENTAIRE', 'CABINET_IDEL', 'CABINET_SAGE_FEMME', 'CABINET_KINE', 'CABINET_ORTHO', 'CABINET_ERGO', 'CABINET_PSYCHOMOT');
CREATE TYPE type_evenement_notification AS ENUM ('NOUVELLE_MISSION_MATCHANT_FILTRE', 'CANDIDATURE_RECUE', 'CANDIDATURE_ACCEPTEE', 'MISSION_ASSIGNEE', 'RAPPEL_J1_MISSION', 'POINTAGE_MANQUANT', 'FACTURE_EMISE', 'PAIEMENT_RECU', 'CONTRAT_TRAVAIL_DEPOSE', 'LITIGE_OUVERT', 'LITIGE_RESOLU', 'DOCUMENT_EXPIRANT', 'MANDAT_RE_SIGNATURE', 'SERIE_ONBOARDING', 'URGENCE', 'NOUVEAU_SOIGNANT_MATCHANT_FILTRE', 'FAVORI_NOUVELLE_MISSION', 'NOTATION_RAPPEL');
CREATE TYPE type_litige AS ENUM ('ABSENCE_SOIGNANT', 'DEPART_ANTICIPE', 'RETARD_IMPORTANT', 'DESACCORD_MONTANT_FACTURE', 'DESACCORD_HEURES_POINTAGE', 'NON_PAIEMENT', 'FRAIS_COMPLEMENTAIRES', 'CONDITIONS_MISSION_NON_RESPECTEES', 'SECURITE_DANGER', 'COMPORTEMENT_SOIGNANT', 'COMPORTEMENT_ETABLISSEMENT', 'AUTRE');
CREATE TYPE type_profession AS ENUM ('IDE', 'AS', 'AES', 'IBODE', 'IADE', 'SAGE_FEMME', 'KINE', 'MEDECIN', 'PHARMACIEN', 'MANIPULATEUR_RADIO', 'PREPARATEUR_PHARMA', 'DIETETICIEN', 'ERGOTHERAPEUTE', 'PSYCHOMOTRICIEN', 'ORTHOPHONISTE', 'DENTISTE', 'AUXILIAIRE_PUERICULTURE');
