-- ============================================================
-- Indexes prod Jolene (pg_indexes, schemaname='public')
-- Extrait le 2026-07-03 — 515 index (PK/UNIQUE inclus)
-- ============================================================

CREATE UNIQUE INDEX admin_invocations_pkey ON public.admin_invocations USING btree (id);
CREATE INDEX idx_admin_inv_function ON public.admin_invocations USING btree (target_function, invoked_at DESC);
CREATE INDEX idx_admin_inv_invoked ON public.admin_invocations USING btree (invoked_at DESC);
CREATE INDEX idx_admin_inv_pending ON public.admin_invocations USING btree (invoked_at) WHERE (completed_at IS NULL);
CREATE INDEX idx_admin_inv_user ON public.admin_invocations USING btree (admin_user_id, invoked_at DESC);
CREATE UNIQUE INDEX admins_groupe_sante_groupe_id_utilisateur_id_key ON public.admins_groupe_sante USING btree (groupe_id, utilisateur_id);
CREATE UNIQUE INDEX admins_groupe_sante_pkey ON public.admins_groupe_sante USING btree (id);
CREATE UNIQUE INDEX alertes_systeme_pkey ON public.alertes_systeme USING btree (id);
CREATE INDEX idx_alertes_systeme_non_resolues ON public.alertes_systeme USING btree (severite, cree_le DESC) WHERE (resolu_le IS NULL);
CREATE INDEX idx_alertes_systeme_type_recent ON public.alertes_systeme USING btree (type_alerte, source, cree_le DESC);
CREATE UNIQUE INDEX api_keys_cle_api_key ON public.api_keys USING btree (cle_api);
CREATE UNIQUE INDEX api_keys_pkey ON public.api_keys USING btree (id);
CREATE INDEX idx_api_keys_etab ON public.api_keys USING btree (etablissement_id);
CREATE INDEX idx_api_keys_groupe ON public.api_keys USING btree (groupe_sante_id);
CREATE UNIQUE INDEX articles_aide_pkey ON public.articles_aide USING btree (id);
CREATE UNIQUE INDEX articles_aide_slug_key ON public.articles_aide USING btree (slug);
CREATE INDEX idx_articles_aide_audience_publie ON public.articles_aide USING btree (audience, publie, ordre_affichage);
CREATE INDEX idx_articles_aide_categorie ON public.articles_aide USING btree (categorie);
CREATE INDEX idx_articles_aide_search ON public.articles_aide USING gin (to_tsvector('french'::regconfig, ((titre || ' '::text) || contenu))) WHERE (publie = true);
CREATE UNIQUE INDEX assurance_config_etablissement_id_key ON public.assurance_config USING btree (etablissement_id);
CREATE UNIQUE INDEX assurance_config_pkey ON public.assurance_config USING btree (id);
CREATE UNIQUE INDEX assurances_mission_pkey ON public.assurances_mission USING btree (id);
CREATE INDEX idx_assurances_etab ON public.assurances_mission USING btree (etablissement_id, statut);
CREATE INDEX idx_assurances_mission ON public.assurances_mission USING btree (mission_id);
CREATE INDEX idx_assurances_sinistre ON public.assurances_mission USING btree (sinistre_statut) WHERE (sinistre_statut IS NOT NULL);
CREATE INDEX idx_assurances_soignant ON public.assurances_mission USING btree (soignant_id, statut);
CREATE UNIQUE INDEX attestations_heures_externes_pkey ON public.attestations_heures_externes USING btree (id);
CREATE UNIQUE INDEX attestations_heures_externes_soignant_id_semaine_du_key ON public.attestations_heures_externes USING btree (soignant_id, semaine_du);
CREATE UNIQUE INDEX avoirs_pkey ON public.avoirs USING btree (id);
CREATE INDEX idx_avoirs_facture_origine ON public.avoirs USING btree (facture_origine_id);
CREATE INDEX idx_avoirs_source_litige ON public.avoirs USING btree (source_litige_id) WHERE (source_litige_id IS NOT NULL);
CREATE INDEX idx_avoirs_source_mission ON public.avoirs USING btree (source_mission_id) WHERE (source_mission_id IS NOT NULL);
CREATE UNIQUE INDEX badges_soignant_pkey ON public.badges_soignant USING btree (id);
CREATE UNIQUE INDEX badges_soignant_soignant_id_badge_type_key ON public.badges_soignant USING btree (soignant_id, badge_type);
CREATE INDEX idx_badges_soignant_id ON public.badges_soignant USING btree (soignant_id, earned_at DESC);
CREATE UNIQUE INDEX bfa_suivi_etablissement_id_annee_key ON public.bfa_suivi USING btree (etablissement_id, annee);
CREATE UNIQUE INDEX bfa_suivi_groupe_id_annee_key ON public.bfa_suivi USING btree (groupe_id, annee);
CREATE UNIQUE INDEX bfa_suivi_pkey ON public.bfa_suivi USING btree (id);
CREATE INDEX idx_bfa_etab ON public.bfa_suivi USING btree (etablissement_id, annee);
CREATE INDEX idx_bfa_groupe ON public.bfa_suivi USING btree (groupe_id, annee);
CREATE UNIQUE INDEX bulletins_paie_pkey ON public.bulletins_paie USING btree (id);
CREATE UNIQUE INDEX bulletins_paie_unique_mission ON public.bulletins_paie USING btree (mission_id);
CREATE UNIQUE INDEX bulletins_paie_unique_numero_par_soignant ON public.bulletins_paie USING btree (soignant_id, numero_bulletin);
CREATE INDEX idx_bp_etablissement ON public.bulletins_paie USING btree (etablissement_id);
CREATE INDEX idx_bp_mission ON public.bulletins_paie USING btree (mission_id);
CREATE INDEX idx_bp_periode ON public.bulletins_paie USING btree (periode_debut DESC);
CREATE INDEX idx_bp_soignant ON public.bulletins_paie USING btree (soignant_id);
CREATE UNIQUE INDEX calendar_connections_pkey ON public.calendar_connections USING btree (id);
CREATE UNIQUE INDEX calendar_connections_utilisateur_id_provider_key ON public.calendar_connections USING btree (utilisateur_id, provider);
CREATE INDEX idx_cal_conn_user ON public.calendar_connections USING btree (utilisateur_id);
CREATE UNIQUE INDEX calendar_events_sync_pkey ON public.calendar_events_sync USING btree (id);
CREATE INDEX idx_cal_sync_connection ON public.calendar_events_sync USING btree (connection_id);
CREATE INDEX idx_cal_sync_mission ON public.calendar_events_sync USING btree (mission_id);
CREATE UNIQUE INDEX candidatures_mission_id_soignant_id_key ON public.candidatures USING btree (mission_id, soignant_id);
CREATE UNIQUE INDEX candidatures_pkey ON public.candidatures USING btree (id);
CREATE INDEX idx_candidatures_mission ON public.candidatures USING btree (mission_id);
CREATE INDEX idx_candidatures_soignant ON public.candidatures USING btree (soignant_id);
CREATE INDEX idx_candidatures_statut ON public.candidatures USING btree (statut);
CREATE UNIQUE INDEX cessions_creance_pkey ON public.cessions_creance USING btree (id);
CREATE UNIQUE INDEX idx_cessions_creance_facture ON public.cessions_creance USING btree (facture_honoraire_id);
CREATE INDEX idx_cessions_creance_soignant ON public.cessions_creance USING btree (soignant_id);
CREATE UNIQUE INDEX chorus_pro_config_etablissement_id_key ON public.chorus_pro_config USING btree (etablissement_id);
CREATE UNIQUE INDEX chorus_pro_config_pkey ON public.chorus_pro_config USING btree (id);
CREATE UNIQUE INDEX chorus_submissions_pkey ON public.chorus_submissions USING btree (id);
CREATE INDEX idx_chorus_sub_avoir ON public.chorus_submissions USING btree (type_document) WHERE (type_document = 'AVOIR'::text);
CREATE INDEX idx_chorus_sub_invoice ON public.chorus_submissions USING btree (invoice_id);
CREATE INDEX idx_chorus_sub_status ON public.chorus_submissions USING btree (status);
CREATE UNIQUE INDEX codes_secours_mission_pkey ON public.codes_secours_mission USING btree (id);
CREATE INDEX idx_codes_secours_actifs ON public.codes_secours_mission USING btree (mission_id, type) WHERE (utilise = false);
CREATE INDEX idx_codes_secours_mission ON public.codes_secours_mission USING btree (mission_id, utilise);
CREATE UNIQUE INDEX conformite_travail_pkey ON public.conformite_travail USING btree (id);
CREATE INDEX idx_conformite_mission ON public.conformite_travail USING btree (mission_id);
CREATE INDEX idx_conformite_soignant ON public.conformite_travail USING btree (soignant_id, controle_le DESC);
CREATE INDEX idx_conformite_violations ON public.conformite_travail USING btree (resultat, controle_le DESC) WHERE (resultat <> 'CONFORME'::text);
CREATE UNIQUE INDEX consentements_ping_gps_pkey ON public.consentements_ping_gps USING btree (soignant_id);
CREATE UNIQUE INDEX contrats_mission_numero_contrat_key ON public.contrats_mission USING btree (numero_contrat);
CREATE UNIQUE INDEX contrats_mission_pkey ON public.contrats_mission USING btree (id);
CREATE INDEX idx_contrats_etab ON public.contrats_mission USING btree (etablissement_id, statut);
CREATE INDEX idx_contrats_mission ON public.contrats_mission USING btree (mission_id);
CREATE INDEX idx_contrats_mission_dpae_numero ON public.contrats_mission USING btree (dpae_numero) WHERE (dpae_numero IS NOT NULL);
CREATE INDEX idx_contrats_mission_storage_path ON public.contrats_mission USING btree (storage_path) WHERE (storage_path IS NOT NULL);
CREATE INDEX idx_contrats_soignant ON public.contrats_mission USING btree (soignant_id, statut);
CREATE UNIQUE INDEX contrats_service_signatures_pkey ON public.contrats_service_signatures USING btree (id);
CREATE UNIQUE INDEX uniq_contrat_service_actif ON public.contrats_service_signatures USING btree (etablissement_id) WHERE (revoked_at IS NULL);
CREATE UNIQUE INDEX contrats_travail_missions_mission_id_key ON public.contrats_travail_missions USING btree (mission_id);
CREATE UNIQUE INDEX contrats_travail_missions_pkey ON public.contrats_travail_missions USING btree (id);
CREATE INDEX idx_contrats_travail_missions_etablissement_id ON public.contrats_travail_missions USING btree (etablissement_id);
CREATE INDEX idx_contrats_travail_missions_soignant_id ON public.contrats_travail_missions USING btree (soignant_id);
CREATE UNIQUE INDEX conversations_participant_1_id_participant_2_id_mission_id_key ON public.conversations USING btree (participant_1_id, participant_2_id, mission_id);
CREATE UNIQUE INDEX conversations_pkey ON public.conversations USING btree (id);
CREATE INDEX idx_conversations_archived_at ON public.conversations USING btree (archived_at) WHERE (archived_at IS NOT NULL);
CREATE INDEX idx_conversations_mission ON public.conversations USING btree (mission_id);
CREATE UNIQUE INDEX conversions_liberal_pkey ON public.conversions_liberal USING btree (id);
CREATE INDEX idx_conversions_soignant ON public.conversions_liberal USING btree (soignant_id);
CREATE UNIQUE INDEX cotisations_sociales_pkey ON public.cotisations_sociales USING btree (id);
CREATE INDEX idx_cotisations_mission ON public.cotisations_sociales USING btree (mission_id);
CREATE INDEX idx_cotisations_soignant ON public.cotisations_sociales USING btree (soignant_id);
CREATE UNIQUE INDEX credits_etablissement_pkey ON public.credits_etablissement USING btree (id);
CREATE INDEX idx_credits_etab ON public.credits_etablissement USING btree (etablissement_id, applique_le);
CREATE INDEX idx_credits_etablissement_facture_id ON public.credits_etablissement USING btree (facture_id);
CREATE UNIQUE INDEX uniq_credits_etab_parrainage ON public.credits_etablissement USING btree (parrainage_id) WHERE (parrainage_id IS NOT NULL);
CREATE UNIQUE INDEX demandes_rgpd_pkey ON public.demandes_rgpd USING btree (id);
CREATE UNIQUE INDEX documents_requis_par_profession_pkey ON public.documents_requis_par_profession USING btree (id);
CREATE UNIQUE INDEX documents_requis_par_profession_profession_type_document_key ON public.documents_requis_par_profession USING btree (profession, type_document);
CREATE UNIQUE INDEX documents_soignants_pkey ON public.documents_soignants USING btree (id);
CREATE INDEX idx_docs_critiques ON public.documents_soignants USING btree (soignant_id, est_critique, valide_jusqua) WHERE ((est_critique = true) AND (supprime_le IS NULL));
CREATE INDEX idx_docs_expiration ON public.documents_soignants USING btree (valide_jusqua) WHERE ((valide_jusqua IS NOT NULL) AND (statut_verification = 'VERIFIE'::statut_verification) AND (supprime_le IS NULL));
CREATE INDEX idx_documents_soignant_type ON public.documents_soignants USING btree (soignant_id, type_document) WHERE (supprime_le IS NULL);
CREATE UNIQUE INDEX email_queue_pkey ON public.email_queue USING btree (id);
CREATE INDEX idx_email_queue_pending ON public.email_queue USING btree (envoye, cree_le) WHERE (envoye = false);
CREATE INDEX idx_email_queue_statut ON public.email_queue USING btree (statut) WHERE (statut = 'EN_ATTENTE'::text);
CREATE UNIQUE INDEX emails_envoyes_pkey ON public.emails_envoyes USING btree (id);
CREATE INDEX idx_emails_dest ON public.emails_envoyes USING btree (destinataire_id, cree_le DESC);
CREATE UNIQUE INDEX uq_emails_bienvenue_destinataire ON public.emails_envoyes USING btree (destinataire_id, type) WHERE ((type = ANY (ARRAY['BIENVENUE_SOIGNANT'::text, 'BIENVENUE_ETABLISSEMENT'::text])) AND (statut <> 'ERREUR'::text));
CREATE UNIQUE INDEX emails_post_mission_mission_id_cible_key ON public.emails_post_mission USING btree (mission_id, cible);
CREATE UNIQUE INDEX emails_post_mission_pkey ON public.emails_post_mission USING btree (id);
CREATE UNIQUE INDEX equipe_admin_pkey ON public.equipe_admin USING btree (id);
CREATE UNIQUE INDEX equipe_admin_user_id_key ON public.equipe_admin USING btree (user_id);
CREATE UNIQUE INDEX equipe_membres_pkey ON public.equipe_membres USING btree (id);
CREATE INDEX idx_equipe_membres_equipe_id ON public.equipe_membres USING btree (equipe_id);
CREATE UNIQUE INDEX equipes_pkey ON public.equipes USING btree (id);
CREATE INDEX idx_equipes_etab ON public.equipes USING btree (etablissement_id) WHERE (supprime_le IS NULL);
CREATE UNIQUE INDEX equivalences_scolarite_pkey ON public.equivalences_scolarite USING btree (id);
CREATE UNIQUE INDEX uq_equiv_scolarite ON public.equivalences_scolarite USING btree (formation, annee_validee_min, profession_autorisee);
CREATE UNIQUE INDEX etablissements_code_parrainage_key ON public.etablissements USING btree (code_parrainage);
CREATE UNIQUE INDEX etablissements_finess_key ON public.etablissements USING btree (finess);
CREATE UNIQUE INDEX etablissements_pkey ON public.etablissements USING btree (id);
CREATE UNIQUE INDEX etablissements_siret_key ON public.etablissements USING btree (siret);
CREATE INDEX idx_etab_palier ON public.etablissements USING btree (palier_commission_id);
CREATE INDEX idx_etab_stripe_customer ON public.etablissements USING btree (stripe_customer_id) WHERE (stripe_customer_id IS NOT NULL);
CREATE INDEX idx_etablissements_groupe ON public.etablissements USING btree (groupe_sante_id) WHERE (groupe_sante_id IS NOT NULL);
CREATE INDEX idx_etablissements_parraine_par_id ON public.etablissements USING btree (parraine_par_id);
CREATE UNIQUE INDEX evaluations_mission_id_evaluateur_id_key ON public.evaluations USING btree (mission_id, evaluateur_id);
CREATE UNIQUE INDEX evaluations_pkey ON public.evaluations USING btree (id);
CREATE INDEX idx_eval_evalue ON public.evaluations USING btree (evalue_id);
CREATE UNIQUE INDEX evenements_score_etab_pkey ON public.evenements_score_etab USING btree (id);
CREATE INDEX idx_evenements_score_etab_litige_id ON public.evenements_score_etab USING btree (litige_id);
CREATE INDEX idx_evenements_score_etab_mission_id ON public.evenements_score_etab USING btree (mission_id);
CREATE INDEX idx_evt_score_etab_etab ON public.evenements_score_etab USING btree (etablissement_id, cree_le DESC);
CREATE UNIQUE INDEX evenements_score_soignant_pkey ON public.evenements_score_soignant USING btree (id);
CREATE INDEX idx_evenements_score_soignant_candidature_id ON public.evenements_score_soignant USING btree (candidature_id);
CREATE INDEX idx_evenements_score_soignant_litige_id ON public.evenements_score_soignant USING btree (litige_id);
CREATE INDEX idx_evenements_score_soignant_mission_id ON public.evenements_score_soignant USING btree (mission_id);
CREATE INDEX idx_evt_score_sg_pending_admin ON public.evenements_score_soignant USING btree (traite_par_admin_id) WHERE ((traite_par_admin_id IS NULL) AND (reclamation_id IS NOT NULL));
CREATE INDEX idx_evt_score_sg_soignant ON public.evenements_score_soignant USING btree (soignant_id, cree_le DESC);
CREATE UNIQUE INDEX exclusions_exclu_par_exclu_id_key ON public.exclusions USING btree (exclu_par, exclu_id);
CREATE UNIQUE INDEX exclusions_pkey ON public.exclusions USING btree (id);
CREATE UNIQUE INDEX externalisation_actions_pkey ON public.externalisation_actions USING btree (id);
CREATE INDEX idx_ext_actions_pending ON public.externalisation_actions USING btree (statut, cree_le) WHERE (statut = ANY (ARRAY['PENDING'::text, 'ERROR'::text]));
CREATE UNIQUE INDEX factor_advances_pkey ON public.factor_advances USING btree (id);
CREATE INDEX idx_factor_advances_etablissement_id ON public.factor_advances USING btree (etablissement_id);
CREATE UNIQUE INDEX idx_factor_advances_facture ON public.factor_advances USING btree (facture_honoraire_id);
CREATE INDEX idx_factor_advances_mission_id ON public.factor_advances USING btree (mission_id);
CREATE INDEX idx_factor_advances_provider_id ON public.factor_advances USING btree (provider, provider_advance_id);
CREATE INDEX idx_factor_advances_soignant ON public.factor_advances USING btree (soignant_id);
CREATE INDEX idx_factor_advances_statut ON public.factor_advances USING btree (statut);
CREATE UNIQUE INDEX factoring_partners_pkey ON public.factoring_partners USING btree (id);
CREATE UNIQUE INDEX factures_numero_facture_key ON public.factures USING btree (numero_facture);
CREATE UNIQUE INDEX factures_pkey ON public.factures USING btree (id);
CREATE INDEX idx_factures_etablissement_statut ON public.factures USING btree (etablissement_id, statut);
CREATE INDEX idx_factures_facture_precedente ON public.factures USING btree (facture_precedente_id) WHERE (facture_precedente_id IS NOT NULL);
CREATE INDEX idx_factures_mission ON public.factures USING btree (mission_id);
CREATE INDEX idx_factures_statut ON public.factures USING btree (statut);
CREATE INDEX idx_factures_statut_emission ON public.factures USING btree (statut, date_emission) WHERE (statut = ANY (ARRAY['EMISE'::text, 'EN_RETARD'::text]));
CREATE INDEX idx_factures_stripe ON public.factures USING btree (stripe_invoice_id) WHERE (stripe_invoice_id IS NOT NULL);
CREATE INDEX idx_factures_type_avoir_fc ON public.factures USING btree (type_document) WHERE (type_document = ANY (ARRAY['AVOIR'::text, 'FACTURE_COMPLEMENTAIRE'::text]));
CREATE UNIQUE INDEX uniq_factures_mission_active ON public.factures USING btree (mission_id) WHERE ((mission_id IS NOT NULL) AND (type_document = 'FACTURE'::text) AND (statut <> ALL (ARRAY['ANNULEE'::text, 'REMPLACEE'::text, 'ERREUR_GENERATION'::text])));
CREATE UNIQUE INDEX factures_honoraires_numero_facture_key ON public.factures_honoraires USING btree (numero_facture);
CREATE UNIQUE INDEX factures_honoraires_pkey ON public.factures_honoraires USING btree (id);
CREATE INDEX idx_factures_honoraires_etab ON public.factures_honoraires USING btree (etablissement_id);
CREATE INDEX idx_factures_honoraires_mission ON public.factures_honoraires USING btree (mission_id);
CREATE INDEX idx_factures_honoraires_soignant ON public.factures_honoraires USING btree (soignant_id);
CREATE INDEX idx_factures_honoraires_statut ON public.factures_honoraires USING btree (statut);
CREATE INDEX idx_fh_facture_precedente ON public.factures_honoraires USING btree (facture_precedente_id) WHERE (facture_precedente_id IS NOT NULL);
CREATE INDEX idx_fh_litige_id ON public.factures_honoraires USING btree (litige_id) WHERE (litige_id IS NOT NULL);
CREATE INDEX idx_fh_mission_periode_fin ON public.factures_honoraires USING btree (mission_id, periode_fin DESC);
CREATE INDEX idx_fh_soignant_iso ON public.factures_honoraires USING btree (soignant_id, annee_iso, numero_semaine_iso) WHERE (annee_iso IS NOT NULL);
CREATE INDEX idx_fh_statut_litige ON public.factures_honoraires USING btree (statut_litige) WHERE (statut_litige <> 'NORMAL'::statut_litige_facture);
CREATE INDEX idx_fh_type_document ON public.factures_honoraires USING btree (type_document) WHERE (type_document = 'AVOIR'::type_document_facture);
CREATE UNIQUE INDEX uniq_factures_honoraires_stripe_pi ON public.factures_honoraires USING btree (stripe_payment_intent_id) WHERE (stripe_payment_intent_id IS NOT NULL);
CREATE UNIQUE INDEX uniq_fh_mission_semaine_active ON public.factures_honoraires USING btree (mission_id, annee_iso, numero_semaine_iso, type_document) WHERE ((est_facture_finale_mission = false) AND (statut <> ALL (ARRAY['ANNULEE'::text, 'REMPLACEE'::text, 'ERREUR_GENERATION'::text])));
CREATE UNIQUE INDEX favoris_etablissement_id_soignant_id_key ON public.favoris_etab_soignant USING btree (etablissement_id, soignant_id);
CREATE UNIQUE INDEX favoris_pkey ON public.favoris_etab_soignant USING btree (id);
CREATE UNIQUE INDEX uq_favoris_soignant_etab ON public.favoris_etab_soignant USING btree (soignant_id, etablissement_id);
CREATE UNIQUE INDEX favoris_soignant_etab_pkey ON public.favoris_soignant_etab USING btree (id);
CREATE UNIQUE INDEX favoris_soignant_etab_soignant_id_etablissement_id_key ON public.favoris_soignant_etab USING btree (soignant_id, etablissement_id);
CREATE INDEX idx_favoris_se_etab ON public.favoris_soignant_etab USING btree (etablissement_id);
CREATE INDEX idx_favoris_se_soignant ON public.favoris_soignant_etab USING btree (soignant_id);
CREATE UNIQUE INDEX file_revue_manuelle_pkey ON public.file_revue_manuelle USING btree (id);
CREATE INDEX idx_file_revue_en_attente ON public.file_revue_manuelle USING btree (statut, priorite DESC, cree_le) WHERE (statut = ANY (ARRAY['EN_ATTENTE'::text, 'EN_COURS_REVUE'::text]));
CREATE UNIQUE INDEX filtres_sauvegardes_pkey ON public.filtres_sauvegardes USING btree (id);
CREATE UNIQUE INDEX filtres_sauvegardes_utilisateur_id_nom_key ON public.filtres_sauvegardes USING btree (utilisateur_id, nom);
CREATE INDEX idx_filtres_sauvegardes_alerte_cron ON public.filtres_sauvegardes USING btree (alerte_active, frequence_alerte, dernier_check_le) WHERE (alerte_active = true);
CREATE UNIQUE INDEX fondateur_documents_pkey ON public.fondateur_documents USING btree (id);
CREATE UNIQUE INDEX groupes_sante_pkey ON public.groupes_sante USING btree (id);
CREATE UNIQUE INDEX groupes_sante_siren_key ON public.groupes_sante USING btree (siren);
CREATE INDEX idx_groupes_parent ON public.groupes_sante USING btree (groupe_parent_id);
CREATE UNIQUE INDEX growth_config_pkey ON public.growth_config USING btree (cle);
CREATE UNIQUE INDEX health_check_pkey ON public.health_check USING btree (id);
CREATE UNIQUE INDEX heures_externes_pkey ON public.heures_externes USING btree (id);
CREATE INDEX idx_heures_ext_soignant ON public.heures_externes USING btree (soignant_id, statut);
CREATE INDEX idx_hext_document ON public.heures_externes USING btree (document_id);
CREATE UNIQUE INDEX heures_externes_soignants_pkey ON public.heures_externes_soignants USING btree (id);
CREATE INDEX idx_heures_externes_soignant ON public.heures_externes_soignants USING btree (soignant_id);
CREATE INDEX idx_heures_externes_soignants_valide_par ON public.heures_externes_soignants USING btree (valide_par);
CREATE UNIQUE INDEX historique_blocages_etablissements_pkey ON public.historique_blocages_etablissements USING btree (id);
CREATE INDEX idx_hist_blocages_etab ON public.historique_blocages_etablissements USING btree (etablissement_id, cree_le DESC);
CREATE UNIQUE INDEX investisseurs_pipeline_pkey ON public.investisseurs_pipeline USING btree (id);
CREATE INDEX idx_invitations_etab_email ON public.invitations_etablissement USING btree (email_invite, statut);
CREATE INDEX idx_invitations_etab_etab ON public.invitations_etablissement USING btree (etablissement_id, statut);
CREATE INDEX idx_invitations_etab_token ON public.invitations_etablissement USING btree (token) WHERE (statut = 'EN_ATTENTE'::text);
CREATE INDEX idx_invitations_etablissement_acceptee_par_user_id ON public.invitations_etablissement USING btree (acceptee_par_user_id);
CREATE INDEX idx_invitations_etablissement_invite_par ON public.invitations_etablissement USING btree (invite_par);
CREATE UNIQUE INDEX invitations_etablissement_pkey ON public.invitations_etablissement USING btree (id);
CREATE UNIQUE INDEX invitations_etablissement_token_key ON public.invitations_etablissement USING btree (token);
CREATE INDEX idx_ial_created ON public.invoice_audit_log USING btree (created_at DESC);
CREATE INDEX idx_ial_invoice ON public.invoice_audit_log USING btree (invoice_id);
CREATE UNIQUE INDEX invoice_audit_log_pkey ON public.invoice_audit_log USING btree (id);
CREATE INDEX idx_audit_acteur ON public.journaux_audit USING btree (acteur_id, cree_le DESC);
CREATE INDEX idx_audit_action ON public.journaux_audit USING btree (action, cree_le DESC);
CREATE INDEX idx_audit_date ON public.journaux_audit USING btree (cree_le DESC);
CREATE INDEX idx_audit_ressource ON public.journaux_audit USING btree (type_ressource, id_ressource, cree_le DESC);
CREATE INDEX idx_audit_s3 ON public.journaux_audit USING btree (cle_s3_ressource) WHERE (cle_s3_ressource IS NOT NULL);
CREATE INDEX idx_journaux_audit_action_acteur ON public.journaux_audit USING btree (action, acteur_id);
CREATE INDEX idx_journaux_audit_ip ON public.journaux_audit USING gin (details) WHERE (details ? 'ip'::text);
CREATE UNIQUE INDEX journaux_audit_pkey ON public.journaux_audit USING btree (id);
CREATE UNIQUE INDEX jours_feries_fr_date_ferie_key ON public.jours_feries_fr USING btree (date_ferie);
CREATE UNIQUE INDEX jours_feries_fr_pkey ON public.jours_feries_fr USING btree (id);
CREATE UNIQUE INDEX liste_attente_premium_pkey ON public.liste_attente_premium USING btree (id);
CREATE UNIQUE INDEX uq_liste_attente ON public.liste_attente_premium USING btree (email, type_offre);
CREATE INDEX idx_litige_mission ON public.litiges USING btree (mission_id);
CREATE INDEX idx_litiges_categorie_ouverts ON public.litiges USING btree (categorie_litige) WHERE (statut = ANY (ARRAY['OUVERT'::text, 'EN_DISCUSSION'::text, 'EN_MEDIATION'::text, 'CONTESTEE'::text]));
CREATE INDEX idx_litiges_escalade_auto ON public.litiges USING btree (escalade_auto_le) WHERE (escalade_auto_le IS NOT NULL);
CREATE INDEX idx_litiges_etablissement_id ON public.litiges USING btree (etablissement_id);
CREATE INDEX idx_litiges_facture_id ON public.litiges USING btree (facture_id) WHERE (facture_id IS NOT NULL);
CREATE INDEX idx_litiges_paiement_soignant_id ON public.litiges USING btree (paiement_soignant_id);
CREATE INDEX idx_litiges_presence ON public.litiges USING btree (presence_id);
CREATE INDEX idx_litiges_soignant_id ON public.litiges USING btree (soignant_id);
CREATE INDEX idx_litiges_statut_ouvert ON public.litiges USING btree (statut) WHERE (statut = ANY (ARRAY['OUVERT'::text, 'EN_DISCUSSION'::text, 'EN_MEDIATION'::text, 'CONTESTEE'::text]));
CREATE INDEX idx_litiges_type_statut_ouverts ON public.litiges USING btree (type_litige, statut) WHERE (statut = ANY (ARRAY['OUVERT'::text, 'EN_DISCUSSION'::text, 'EN_MEDIATION'::text, 'CONTESTEE'::text]));
CREATE UNIQUE INDEX litiges_pkey ON public.litiges USING btree (id);
CREATE UNIQUE INDEX uq_litige_mission_type_ouvert ON public.litiges USING btree (mission_id, type_litige) WHERE (statut = ANY (ARRAY['OUVERT'::text, 'EN_DISCUSSION'::text, 'EN_MEDIATION'::text]));
CREATE INDEX idx_mandats_soignant ON public.mandats_facturation_signatures USING btree (soignant_id, signed_at DESC);
CREATE UNIQUE INDEX mandats_facturation_signatures_pkey ON public.mandats_facturation_signatures USING btree (id);
CREATE UNIQUE INDEX marche_taux_medians_pkey ON public.marche_taux_medians USING btree (profession);
CREATE UNIQUE INDEX matching_preferences_soignant_pkey ON public.matching_preferences_soignant USING btree (soignant_id);
CREATE INDEX idx_matching_scores_calcule_le ON public.matching_scores USING btree (calcule_le);
CREATE INDEX idx_matching_scores_mission ON public.matching_scores USING btree (mission_id);
CREATE INDEX idx_matching_scores_soignant_score ON public.matching_scores USING btree (soignant_id, score_global DESC);
CREATE UNIQUE INDEX matching_scores_pkey ON public.matching_scores USING btree (id);
CREATE UNIQUE INDEX matching_scores_soignant_id_mission_id_key ON public.matching_scores USING btree (soignant_id, mission_id);
CREATE INDEX idx_membres_etab_etab ON public.membres_etablissement USING btree (etablissement_id) WHERE (actif = true);
CREATE INDEX idx_membres_etab_user ON public.membres_etablissement USING btree (user_id) WHERE (actif = true);
CREATE INDEX idx_membres_etablissement_invite_par ON public.membres_etablissement USING btree (invite_par);
CREATE UNIQUE INDEX membres_etablissement_etablissement_id_user_id_key ON public.membres_etablissement USING btree (etablissement_id, user_id);
CREATE UNIQUE INDEX membres_etablissement_pkey ON public.membres_etablissement USING btree (id);
CREATE INDEX idx_messages_chat_conversation ON public.messages_chat USING btree (conversation_id, cree_le DESC);
CREATE INDEX idx_msg_chat_auteur ON public.messages_chat USING btree (auteur_id);
CREATE INDEX idx_msg_chat_conversation ON public.messages_chat USING btree (conversation_id);
CREATE UNIQUE INDEX messages_chat_pkey ON public.messages_chat USING btree (id);
CREATE UNIQUE INDEX messages_contact_pkey ON public.messages_contact USING btree (id);
CREATE INDEX idx_messages_litige_litige_id ON public.messages_litige USING btree (litige_id);
CREATE UNIQUE INDEX messages_litige_pkey ON public.messages_litige USING btree (id);
CREATE INDEX idx_msg_mission ON public.messages_mission USING btree (mission_id, cree_le);
CREATE UNIQUE INDEX messages_mission_pkey ON public.messages_mission USING btree (id);
CREATE INDEX idx_mc_mission ON public.mission_creneaux USING btree (mission_id);
CREATE UNIQUE INDEX mission_creneaux_pkey ON public.mission_creneaux USING btree (id);
CREATE UNIQUE INDEX uq_mission_creneau_ordre ON public.mission_creneaux USING btree (mission_id, ordre);
CREATE INDEX idx_ms_etablissement ON public.mission_series USING btree (etablissement_id);
CREATE UNIQUE INDEX mission_series_pkey ON public.mission_series USING btree (id);
CREATE INDEX idx_missions_absence_sans_prevenir ON public.missions USING btree (soignant_assigne_id, statut, absence_sans_prevenir) WHERE (absence_sans_prevenir = true);
CREATE INDEX idx_missions_commission ON public.missions USING btree (etablissement_id, commission_facturee) WHERE ((statut = 'TERMINEE'::statut_mission) AND (commission_facturee = false));
CREATE INDEX idx_missions_debut ON public.missions USING btree (debut_le);
CREATE INDEX idx_missions_debut_le ON public.missions USING btree (debut_le DESC);
CREATE INDEX idx_missions_etab_debut ON public.missions USING btree (etablissement_id, debut_le);
CREATE INDEX idx_missions_etablissement_statut ON public.missions USING btree (etablissement_id, statut);
CREATE INDEX idx_missions_facture_id ON public.missions USING btree (facture_id) WHERE (facture_id IS NOT NULL);
CREATE INDEX idx_missions_profession ON public.missions USING btree (profession_requise, statut, debut_le);
CREATE INDEX idx_missions_profession_statut ON public.missions USING btree (profession_requise, statut);
CREATE INDEX idx_missions_search ON public.missions USING gin (to_tsvector('french'::regconfig, ((((COALESCE(intitule, ''::text) || ' '::text) || COALESCE(service, ''::text)) || ' '::text) || COALESCE(description, ''::text)))) WHERE (statut = 'OUVERTE'::statut_mission);
CREATE INDEX idx_missions_serie ON public.missions USING btree (serie_id) WHERE (serie_id IS NOT NULL);
CREATE INDEX idx_missions_soignant ON public.missions USING btree (soignant_assigne_id, statut);
CREATE INDEX idx_missions_soignant_etab_statut ON public.missions USING btree (soignant_assigne_id, etablissement_id, statut);
CREATE INDEX idx_missions_soignant_statut ON public.missions USING btree (soignant_assigne_id, statut) WHERE (soignant_assigne_id IS NOT NULL);
CREATE INDEX idx_missions_specialite_medicale_requise ON public.missions USING btree (specialite_medicale_requise);
CREATE INDEX idx_missions_statut ON public.missions USING btree (statut);
CREATE INDEX idx_missions_statut_fin_le ON public.missions USING btree (statut, fin_le) WHERE (statut = ANY (ARRAY['EN_COURS'::statut_mission, 'TERMINEE'::statut_mission, 'ASSIGNEE'::statut_mission]));
CREATE INDEX idx_missions_terminee_salarie ON public.missions USING btree (fin_le, statut, type_contrat_applique) WHERE (statut = 'TERMINEE'::statut_mission);
CREATE INDEX idx_missions_urgentes ON public.missions USING btree (est_urgente, statut, debut_le) WHERE ((est_urgente = true) AND (statut = 'OUVERTE'::statut_mission));
CREATE UNIQUE INDEX missions_pkey ON public.missions USING btree (id);
CREATE INDEX idx_missions_sauvegardees_mission ON public.missions_sauvegardees USING btree (mission_id);
CREATE INDEX idx_missions_sauvegardees_soignant ON public.missions_sauvegardees USING btree (soignant_id);
CREATE UNIQUE INDEX missions_sauvegardees_pkey ON public.missions_sauvegardees USING btree (id);
CREATE UNIQUE INDEX missions_sauvegardees_soignant_id_mission_id_key ON public.missions_sauvegardees USING btree (soignant_id, mission_id);
CREATE INDEX idx_notations_mission ON public.notations_missions USING btree (mission_id);
CREATE INDEX idx_notations_notateur ON public.notations_missions USING btree (notateur_id);
CREATE INDEX idx_notations_note_id ON public.notations_missions USING btree (note_id, sens, cree_le DESC);
CREATE UNIQUE INDEX notations_missions_mission_id_sens_key ON public.notations_missions USING btree (mission_id, sens);
CREATE UNIQUE INDEX notations_missions_pkey ON public.notations_missions USING btree (id);
CREATE INDEX idx_notif_destinataire ON public.notifications USING btree (destinataire_id, lue, cree_le DESC);
CREATE INDEX idx_notif_push ON public.notifications USING btree (push_envoyee, cree_le DESC) WHERE (push_envoyee = false);
CREATE INDEX idx_notif_type ON public.notifications USING btree (type, cree_le DESC);
CREATE INDEX idx_notifications_destinataire_nonlue ON public.notifications USING btree (destinataire_id, lue) WHERE (lue = false);
CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);
CREATE INDEX idx_notif_notation_j1_dest ON public.notifications_notation_j1 USING btree (destinataire_id, envoye_le DESC);
CREATE UNIQUE INDEX notifications_notation_j1_mission_id_sens_key ON public.notifications_notation_j1 USING btree (mission_id, sens);
CREATE UNIQUE INDEX notifications_notation_j1_pkey ON public.notifications_notation_j1 USING btree (id);
CREATE INDEX idx_otps_telephone_phone ON public.otps_telephone USING btree (telephone, cree_le DESC);
CREATE INDEX idx_otps_telephone_user ON public.otps_telephone USING btree (user_id, cree_le DESC);
CREATE UNIQUE INDEX otps_telephone_pkey ON public.otps_telephone USING btree (id);
CREATE INDEX idx_paiements_etab ON public.paiements_mission USING btree (etablissement_id);
CREATE INDEX idx_paiements_mission ON public.paiements_mission USING btree (mission_id);
CREATE UNIQUE INDEX paiements_mission_pkey ON public.paiements_mission USING btree (id);
CREATE UNIQUE INDEX uniq_paiements_mission_stripe_pi ON public.paiements_mission USING btree (stripe_payment_intent_id) WHERE (stripe_payment_intent_id IS NOT NULL);
CREATE UNIQUE INDEX uq_paiements_mission_mission_id ON public.paiements_mission USING btree (mission_id);
CREATE INDEX idx_paie_etab ON public.paiements_soignant USING btree (etablissement_id);
CREATE INDEX idx_paie_soignant ON public.paiements_soignant USING btree (soignant_id);
CREATE INDEX idx_paiements_soignant_mission ON public.paiements_soignant USING btree (mission_id);
CREATE INDEX idx_paiements_soignant_statut ON public.paiements_soignant USING btree (statut);
CREATE UNIQUE INDEX paiements_soignant_pkey ON public.paiements_soignant USING btree (id);
CREATE UNIQUE INDEX paliers_bfa_pkey ON public.paliers_bfa USING btree (id);
CREATE UNIQUE INDEX paliers_commission_pkey ON public.paliers_commission USING btree (id);
CREATE UNIQUE INDEX parametres_litiges_pkey ON public.parametres_litiges USING btree (cle);
CREATE UNIQUE INDEX parametres_systeme_pkey ON public.parametres_systeme USING btree (cle);
CREATE INDEX idx_parcours_liberal_soignant ON public.parcours_liberal_soignants USING btree (soignant_id);
CREATE UNIQUE INDEX parcours_liberal_soignants_pkey ON public.parcours_liberal_soignants USING btree (id);
CREATE UNIQUE INDEX parcours_liberal_soignants_soignant_id_key ON public.parcours_liberal_soignants USING btree (soignant_id);
CREATE INDEX idx_fraude_signals_parrainage ON public.parrainage_fraude_signals USING btree (parrainage_id);
CREATE UNIQUE INDEX parrainage_fraude_signals_pkey ON public.parrainage_fraude_signals USING btree (id);
CREATE INDEX idx_parrainages_statut_filleul ON public.parrainages USING btree (filleul_id, statut) WHERE (statut = ANY (ARRAY['EN_ATTENTE'::text, 'FILLEUL_ACTIF'::text, 'VALIDE_EN_ATTENTE_SEUIL'::text]));
CREATE UNIQUE INDEX parrainages_parrain_id_filleul_id_key ON public.parrainages USING btree (parrain_id, filleul_id);
CREATE UNIQUE INDEX parrainages_pkey ON public.parrainages USING btree (id);
CREATE INDEX idx_parrainages_etab_filleul ON public.parrainages_etablissements USING btree (filleul_etab_id);
CREATE INDEX idx_parrainages_etab_parrain ON public.parrainages_etablissements USING btree (parrain_etab_id);
CREATE UNIQUE INDEX parrainages_etablissements_filleul_etab_id_key ON public.parrainages_etablissements USING btree (filleul_etab_id);
CREATE UNIQUE INDEX parrainages_etablissements_pkey ON public.parrainages_etablissements USING btree (id);
CREATE INDEX idx_partage_rib_etab ON public.partages_rib USING btree (etablissement_id);
CREATE INDEX idx_partage_rib_mission ON public.partages_rib USING btree (mission_id);
CREATE INDEX idx_partage_rib_soignant ON public.partages_rib USING btree (soignant_id);
CREATE INDEX idx_partages_rib_contrat ON public.partages_rib USING btree (contrat_id);
CREATE INDEX idx_partages_rib_document ON public.partages_rib USING btree (document_rib_id) WHERE (document_rib_id IS NOT NULL);
CREATE UNIQUE INDEX partages_rib_pkey ON public.partages_rib USING btree (id);
CREATE INDEX idx_pauses_presence ON public.pauses_presence USING btree (presence_id);
CREATE INDEX idx_pauses_soignant ON public.pauses_presence USING btree (soignant_id);
CREATE UNIQUE INDEX pauses_presence_pkey ON public.pauses_presence USING btree (id);
CREATE INDEX idx_pings_gps_mission ON public.pings_gps_mission USING btree (mission_id, horodatage DESC);
CREATE INDEX idx_pings_gps_purge ON public.pings_gps_mission USING btree (recu_le);
CREATE INDEX idx_pings_gps_soignant ON public.pings_gps_mission USING btree (soignant_id, horodatage DESC);
CREATE UNIQUE INDEX pings_gps_mission_pkey ON public.pings_gps_mission USING btree (id);
CREATE UNIQUE INDEX plans_prevoyance_pkey ON public.plans_prevoyance USING btree (id);
CREATE UNIQUE INDEX preferences_notifications_pkey ON public.preferences_notifications USING btree (utilisateur_id);
CREATE INDEX idx_pn_pe_user_event_canal ON public.preferences_notifications_par_evenement USING btree (utilisateur_id, type_evenement, canal);
CREATE UNIQUE INDEX preferences_notifications_par_evenement_pkey ON public.preferences_notifications_par_evenement USING btree (id);
CREATE UNIQUE INDEX preferences_notifications_par_utilisateur_id_type_evenement_key ON public.preferences_notifications_par_evenement USING btree (utilisateur_id, type_evenement, canal);
CREATE INDEX idx_presence_status_last_seen ON public.presence_status USING btree (last_seen_at);
CREATE UNIQUE INDEX presence_status_pkey ON public.presence_status USING btree (user_id);
CREATE INDEX idx_presences_ajustement_litige_id ON public.presences USING btree (ajustement_litige_id) WHERE (ajustement_litige_id IS NOT NULL);
CREATE INDEX idx_presences_coherence_pending ON public.presences USING btree (pointage_arrivee_le) WHERE (coherence_verifiee_le IS NULL);
CREATE INDEX idx_presences_fraude ON public.presences USING btree (alerte_teleportation) WHERE (alerte_teleportation = true);
CREATE INDEX idx_presences_mission ON public.presences USING btree (mission_id);
CREATE INDEX idx_presences_soignant ON public.presences USING btree (soignant_id, pointage_arrivee_le DESC);
CREATE UNIQUE INDEX presences_mission_id_soignant_id_key ON public.presences USING btree (mission_id, soignant_id);
CREATE UNIQUE INDEX presences_pkey ON public.presences USING btree (id);
CREATE INDEX idx_prevoyance_la_cree ON public.prevoyance_liste_attente USING btree (cree_le DESC);
CREATE INDEX idx_prevoyance_la_soignant ON public.prevoyance_liste_attente USING btree (soignant_id);
CREATE UNIQUE INDEX prevoyance_liste_attente_email_key ON public.prevoyance_liste_attente USING btree (email);
CREATE UNIQUE INDEX prevoyance_liste_attente_pkey ON public.prevoyance_liste_attente USING btree (id);
CREATE UNIQUE INDEX professions_liberal_eligible_pkey ON public.professions_liberal_eligible USING btree (profession);
CREATE INDEX idx_prospects_etab_a_enrichir ON public.prospects_etablissements USING btree (maj_le) WHERE (enrichi_le IS NULL);
CREATE INDEX idx_prospects_etab_dept ON public.prospects_etablissements USING btree (departement);
CREATE INDEX idx_prospects_etab_email_a_envoyer ON public.prospects_etablissements USING btree (email) WHERE ((email IS NOT NULL) AND (email_envoye_le IS NULL));
CREATE INDEX idx_prospects_etab_favori ON public.prospects_etablissements USING btree (favori) WHERE favori;
CREATE INDEX idx_prospects_etab_nom_trgm ON public.prospects_etablissements USING gin (nom gin_trgm_ops);
CREATE INDEX idx_prospects_etab_type ON public.prospects_etablissements USING btree (type_jolene);
CREATE INDEX idx_prospects_etab_ville_trgm ON public.prospects_etablissements USING gin (ville gin_trgm_ops);
CREATE UNIQUE INDEX prospects_etablissements_pkey ON public.prospects_etablissements USING btree (finess);
CREATE INDEX idx_prospects_soign_enseigne_trgm ON public.prospects_soignants USING gin (enseigne gin_trgm_ops);
CREATE INDEX idx_prospects_soign_nom_trgm ON public.prospects_soignants USING gin (nom gin_trgm_ops);
CREATE INDEX idx_prospects_soign_ville_trgm ON public.prospects_soignants USING gin (ville gin_trgm_ops);
CREATE INDEX idx_prospects_soignants_a_enrichir ON public.prospects_soignants USING btree (maj_le) WHERE (enrichi_le IS NULL);
CREATE INDEX idx_prospects_soignants_email_a_envoyer ON public.prospects_soignants USING btree (email) WHERE ((email IS NOT NULL) AND (email_envoye_le IS NULL));
CREATE INDEX idx_prospects_soignants_etudiant ON public.prospects_soignants USING btree (est_etudiant) WHERE est_etudiant;
CREATE INDEX idx_prospects_soignants_prof_dep ON public.prospects_soignants USING btree (profession, departement);
CREATE UNIQUE INDEX prospects_soignants_pkey ON public.prospects_soignants USING btree (cle);
CREATE UNIQUE INDEX psc_auth_sessions_pkey ON public.psc_auth_sessions USING btree (state);
CREATE INDEX idx_qr_codes_actifs ON public.qr_codes_mission USING btree (mission_id, type) WHERE (actif = true);
CREATE INDEX idx_qr_codes_mission ON public.qr_codes_mission USING btree (mission_id);
CREATE INDEX idx_qr_codes_token ON public.qr_codes_mission USING btree (token) WHERE (actif = true);
CREATE UNIQUE INDEX qr_codes_mission_pkey ON public.qr_codes_mission USING btree (id);
CREATE UNIQUE INDEX qr_codes_mission_token_key ON public.qr_codes_mission USING btree (token);
CREATE UNIQUE INDEX rappels_contrat_travail_pkey ON public.rappels_contrat_travail USING btree (id);
CREATE UNIQUE INDEX uniq_rappel_mission_jour ON public.rappels_contrat_travail USING btree (mission_id, envoye_le);
CREATE INDEX idx_rate_limits_cle_action ON public.rate_limits USING btree (cle, action);
CREATE INDEX idx_rate_limits_expire ON public.rate_limits USING btree (premiere_tentative);
CREATE UNIQUE INDEX rate_limits_pkey ON public.rate_limits USING btree (id);
CREATE INDEX idx_reclamations_cree_le ON public.reclamations USING btree (cree_le DESC);
CREATE INDEX idx_reclamations_mission_id ON public.reclamations USING btree (mission_id);
CREATE INDEX idx_reclamations_statut ON public.reclamations USING btree (statut);
CREATE INDEX idx_reclamations_traite_par ON public.reclamations USING btree (traite_par);
CREATE INDEX idx_reclamations_utilisateur ON public.reclamations USING btree (utilisateur_id);
CREATE UNIQUE INDEX reclamations_pkey ON public.reclamations USING btree (id);
CREATE INDEX idx_rec_score_contesteur ON public.reclamations_score USING btree (contesteur_id);
CREATE INDEX idx_rec_score_evt_etab ON public.reclamations_score USING btree (evenement_etab_id) WHERE (evenement_etab_id IS NOT NULL);
CREATE INDEX idx_rec_score_evt_soignant ON public.reclamations_score USING btree (evenement_soignant_id) WHERE (evenement_soignant_id IS NOT NULL);
CREATE INDEX idx_rec_score_pending ON public.reclamations_score USING btree (statut, cree_le) WHERE (statut = 'PENDING'::text);
CREATE UNIQUE INDEX reclamations_score_pkey ON public.reclamations_score USING btree (id);
CREATE INDEX idx_reclamations_mission ON public.reclamations_scoring USING btree (mission_id);
CREATE INDEX idx_reclamations_soignant ON public.reclamations_scoring USING btree (soignant_id);
CREATE UNIQUE INDEX reclamations_scoring_pkey ON public.reclamations_scoring USING btree (id);
CREATE UNIQUE INDEX regles_exercice_profession_pkey ON public.regles_exercice_profession USING btree (profession);
CREATE INDEX idx_relances_soignant ON public.relances_soignants USING btree (soignant_id, envoye_le DESC);
CREATE UNIQUE INDEX relances_soignants_pkey ON public.relances_soignants USING btree (id);
CREATE UNIQUE INDEX rist_plafonds_pkey ON public.rist_plafonds USING btree (id);
CREATE UNIQUE INDEX rist_plafonds_profession_type_contrat_en_vigueur_depuis_key ON public.rist_plafonds USING btree (profession, type_contrat, en_vigueur_depuis);
CREATE UNIQUE INDEX rpps_test_pkey ON public.rpps_test USING btree (rpps);
CREATE UNIQUE INDEX sales_annuaires_pkey ON public.sales_annuaires USING btree (id);
CREATE INDEX idx_sales_contacts_groupe_id ON public.sales_contacts USING btree (groupe_id);
CREATE UNIQUE INDEX sales_contacts_pkey ON public.sales_contacts USING btree (id);
CREATE UNIQUE INDEX uq_sales_contacts_finess ON public.sales_contacts USING btree (finess);
CREATE UNIQUE INDEX sales_groupes_pkey ON public.sales_groupes USING btree (id);
CREATE UNIQUE INDEX sales_templates_pkey ON public.sales_templates USING btree (id);
CREATE INDEX idx_scans_pointage_code ON public.scans_pointage USING btree (code_saisi);
CREATE INDEX idx_scans_pointage_creneau_effectif_id ON public.scans_pointage USING btree (creneau_effectif_id);
CREATE INDEX idx_scans_pointage_mission ON public.scans_pointage USING btree (mission_id, numero_scan);
CREATE INDEX idx_scans_pointage_soignant_id ON public.scans_pointage USING btree (soignant_id);
CREATE INDEX idx_scans_pointage_valide_par ON public.scans_pointage USING btree (valide_par);
CREATE UNIQUE INDEX scans_pointage_pkey ON public.scans_pointage USING btree (id);
CREATE INDEX idx_scoring_breakdown_soignant ON public.scoring_breakdown USING btree (soignant_id, cree_le DESC);
CREATE UNIQUE INDEX scoring_breakdown_pkey ON public.scoring_breakdown USING btree (id);
CREATE INDEX idx_serie_email_a_traiter ON public.serie_email_envois USING btree (statut, planifie_le) WHERE (statut = 'PLANIFIE'::serie_email_statut);
CREATE UNIQUE INDEX serie_email_envois_pkey ON public.serie_email_envois USING btree (id);
CREATE UNIQUE INDEX serie_email_envois_utilisateur_id_serie_etape_key ON public.serie_email_envois USING btree (utilisateur_id, serie, etape);
CREATE INDEX idx_shift_affectations_mission_id ON public.shift_affectations USING btree (mission_id);
CREATE INDEX idx_shift_affectations_shift ON public.shift_affectations USING btree (shift_id);
CREATE INDEX idx_shift_affectations_soignant ON public.shift_affectations USING btree (soignant_id);
CREATE UNIQUE INDEX shift_affectations_pkey ON public.shift_affectations USING btree (id);
CREATE INDEX idx_shifts_equipe ON public.shifts USING btree (equipe_id);
CREATE INDEX idx_shifts_etab_jour ON public.shifts USING btree (etablissement_id, jour);
CREATE UNIQUE INDEX shifts_pkey ON public.shifts USING btree (id);
CREATE INDEX idx_signalements_cible ON public.signalements USING btree (cible_id);
CREATE INDEX idx_signalements_statut ON public.signalements USING btree (statut, cree_le DESC);
CREATE UNIQUE INDEX signalements_pkey ON public.signalements USING btree (id);
CREATE INDEX idx_signature_rate_limit_ip_action ON public.signature_rate_limit_ip USING btree (derniere_action);
CREATE UNIQUE INDEX signature_rate_limit_ip_pkey ON public.signature_rate_limit_ip USING btree (ip_signature, fenetre_debut);
CREATE INDEX idx_signatures_contrats_contrat ON public.signatures_contrats USING btree (contrat_id);
CREATE INDEX idx_signatures_contrats_ip ON public.signatures_contrats USING btree (ip_signature) WHERE (ip_signature IS NOT NULL);
CREATE INDEX idx_signatures_contrats_user ON public.signatures_contrats USING btree (signataire_user_id);
CREATE UNIQUE INDEX signatures_contrats_contrat_id_signataire_role_key ON public.signatures_contrats USING btree (contrat_id, signataire_role);
CREATE UNIQUE INDEX signatures_contrats_pkey ON public.signatures_contrats USING btree (id);
CREATE INDEX idx_sms_anti_spam ON public.sms_envoyes USING btree (destinataire_id, type, cree_le DESC);
CREATE INDEX idx_sms_destinataire ON public.sms_envoyes USING btree (destinataire_id, cree_le DESC);
CREATE UNIQUE INDEX sms_envoyes_idempotency_key_uniq ON public.sms_envoyes USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE UNIQUE INDEX sms_envoyes_pkey ON public.sms_envoyes USING btree (id);
CREATE INDEX idx_soignants_activite ON public.soignants USING btree (derniere_activite_le) WHERE (supprime_le IS NULL);
CREATE INDEX idx_soignants_conversion ON public.soignants USING btree (heures_cumulees) WHERE ((eligible_conversion_3200h = false) AND (supprime_le IS NULL));
CREATE INDEX idx_soignants_docs_valides ON public.soignants USING btree (tous_documents_valides) WHERE (supprime_le IS NULL);
CREATE INDEX idx_soignants_fiabilite ON public.soignants USING btree (score_fiabilite DESC) WHERE (supprime_le IS NULL);
CREATE INDEX idx_soignants_geo ON public.soignants USING btree (adresse_lat, adresse_lng) WHERE ((supprime_le IS NULL) AND (adresse_lat IS NOT NULL));
CREATE INDEX idx_soignants_profession ON public.soignants USING btree (profession) WHERE (supprime_le IS NULL);
CREATE INDEX idx_soignants_profession_actif ON public.soignants USING btree (profession, supprime_le) WHERE (supprime_le IS NULL);
CREATE INDEX idx_soignants_psc_sub ON public.soignants USING btree (psc_sub) WHERE (psc_sub IS NOT NULL);
CREATE INDEX idx_soignants_score_breakdown_id ON public.soignants USING btree (score_breakdown_id);
CREATE INDEX idx_soignants_specialite_medicale ON public.soignants USING btree (specialite_medicale);
CREATE INDEX idx_soignants_statut_compte ON public.soignants USING btree (statut_compte) WHERE (statut_compte <> 'ACTIF'::statut_compte_soignant);
CREATE UNIQUE INDEX soignants_code_parrainage_key ON public.soignants USING btree (code_parrainage);
CREATE UNIQUE INDEX soignants_email_key ON public.soignants USING btree (email);
CREATE UNIQUE INDEX soignants_numero_adeli_key ON public.soignants USING btree (numero_adeli);
CREATE UNIQUE INDEX soignants_numero_rpps_key ON public.soignants USING btree (numero_rpps);
CREATE UNIQUE INDEX soignants_pkey ON public.soignants USING btree (id);
CREATE UNIQUE INDEX soignants_psc_sub_key ON public.soignants USING btree (psc_sub);
CREATE INDEX idx_prevoyance_plan ON public.souscriptions_prevoyance USING btree (plan_id);
CREATE UNIQUE INDEX souscriptions_prevoyance_pkey ON public.souscriptions_prevoyance USING btree (id);
CREATE UNIQUE INDEX souscriptions_prevoyance_soignant_id_plan_id_key ON public.souscriptions_prevoyance USING btree (soignant_id, plan_id);
CREATE UNIQUE INDEX specialites_medicales_pkey ON public.specialites_medicales USING btree (code);
CREATE UNIQUE INDEX statut_services_api_nom_service_key ON public.statut_services_api USING btree (nom_service);
CREATE UNIQUE INDEX statut_services_api_pkey ON public.statut_services_api USING btree (id);
CREATE INDEX idx_streaks_soignant_last_activity ON public.streaks_soignant USING btree (last_activity_date);
CREATE UNIQUE INDEX streaks_soignant_pkey ON public.streaks_soignant USING btree (soignant_id);
CREATE INDEX idx_stripe_connect_account ON public.stripe_connect_onboarding USING btree (stripe_account_id) WHERE (stripe_account_id IS NOT NULL);
CREATE INDEX idx_stripe_connect_soignant ON public.stripe_connect_onboarding USING btree (soignant_id);
CREATE UNIQUE INDEX stripe_connect_onboarding_pkey ON public.stripe_connect_onboarding USING btree (id);
CREATE UNIQUE INDEX stripe_connect_onboarding_soignant_id_key ON public.stripe_connect_onboarding USING btree (soignant_id);
CREATE INDEX idx_stripe_refunds_queue_avoir_id ON public.stripe_refunds_queue USING btree (avoir_id);
CREATE INDEX idx_stripe_refunds_queue_facture_origine_id ON public.stripe_refunds_queue USING btree (facture_origine_id);
CREATE INDEX idx_stripe_refunds_queue_statut ON public.stripe_refunds_queue USING btree (statut, cree_le) WHERE (statut = ANY (ARRAY['EN_ATTENTE'::text, 'EN_COURS'::text]));
CREATE UNIQUE INDEX stripe_refunds_queue_pkey ON public.stripe_refunds_queue USING btree (id);
CREATE INDEX idx_stripe_transfers_facture ON public.stripe_transfers USING btree (facture_id) WHERE (facture_id IS NOT NULL);
CREATE INDEX idx_transfers_dispute_id ON public.stripe_transfers USING btree (dispute_id) WHERE (dispute_id IS NOT NULL);
CREATE INDEX idx_transfers_etab ON public.stripe_transfers USING btree (etablissement_id);
CREATE INDEX idx_transfers_mission ON public.stripe_transfers USING btree (mission_id);
CREATE INDEX idx_transfers_soignant ON public.stripe_transfers USING btree (soignant_id);
CREATE INDEX idx_transfers_stripe_charge_id ON public.stripe_transfers USING btree (stripe_charge_id) WHERE (stripe_charge_id IS NOT NULL);
CREATE INDEX idx_transfers_stripe_payout ON public.stripe_transfers USING btree (stripe_payout_id) WHERE (stripe_payout_id IS NOT NULL);
CREATE INDEX idx_transfers_stripe_pi ON public.stripe_transfers USING btree (stripe_payment_intent_id) WHERE (stripe_payment_intent_id IS NOT NULL);
CREATE INDEX idx_transfers_stripe_transfer_id ON public.stripe_transfers USING btree (stripe_transfer_id) WHERE (stripe_transfer_id IS NOT NULL);
CREATE UNIQUE INDEX stripe_transfers_pkey ON public.stripe_transfers USING btree (id);
CREATE UNIQUE INDEX stripe_webhook_events_pkey ON public.stripe_webhook_events USING btree (event_id);
CREATE UNIQUE INDEX suivi_conversion_3200h_pkey ON public.suivi_conversion_3200h USING btree (id);
CREATE UNIQUE INDEX suivi_conversion_3200h_soignant_id_key ON public.suivi_conversion_3200h USING btree (soignant_id);
CREATE INDEX idx_super_swipes_quota_soignant_date ON public.super_swipes_quota USING btree (soignant_id, date);
CREATE UNIQUE INDEX super_swipes_quota_pkey ON public.super_swipes_quota USING btree (id);
CREATE UNIQUE INDEX super_swipes_quota_soignant_id_date_key ON public.super_swipes_quota USING btree (soignant_id, date);
CREATE INDEX idx_swipes_mission_direction ON public.swipes USING btree (mission_id, direction);
CREATE INDEX idx_swipes_soignant_created ON public.swipes USING btree (soignant_id, created_at DESC);
CREATE UNIQUE INDEX swipes_pkey ON public.swipes USING btree (id);
CREATE UNIQUE INDEX swipes_soignant_id_mission_id_key ON public.swipes USING btree (soignant_id, mission_id);
CREATE UNIQUE INDEX templates_contrat_pkey ON public.templates_contrat USING btree (id);
CREATE UNIQUE INDEX tokens_calendrier_pkey ON public.tokens_calendrier USING btree (id);
CREATE UNIQUE INDEX tokens_calendrier_soignant_id_key ON public.tokens_calendrier USING btree (soignant_id);
CREATE INDEX idx_tokens_user ON public.tokens_push USING btree (utilisateur_id, actif);
CREATE UNIQUE INDEX tokens_push_pkey ON public.tokens_push USING btree (id);
CREATE UNIQUE INDEX tokens_push_utilisateur_id_token_key ON public.tokens_push USING btree (utilisateur_id, token);
CREATE INDEX idx_typing_status_started_at ON public.typing_status USING btree (started_at);
CREATE INDEX idx_typing_status_user_id ON public.typing_status USING btree (user_id);
CREATE UNIQUE INDEX typing_status_pkey ON public.typing_status USING btree (conversation_id, user_id);
