-- ============================================================
-- Triggers prod Jolene (pg_trigger, non-internes, schéma public)
-- Extrait le 2026-07-03 — 187 triggers
-- ============================================================

CREATE TRIGGER trg_admin_inv_append_only BEFORE DELETE OR UPDATE ON public.admin_invocations FOR EACH ROW EXECUTE FUNCTION fn_admin_invocations_append_only();
CREATE TRIGGER trg_protect_api_key_secrets BEFORE UPDATE ON public.api_keys FOR EACH ROW EXECUTE FUNCTION fn_protect_api_key_secrets();
CREATE TRIGGER trg_articles_aide_updated_at BEFORE UPDATE ON public.articles_aide FOR EACH ROW EXECUTE FUNCTION fn_trg_articles_aide_updated_at();
CREATE TRIGGER trg_bp_immutability BEFORE UPDATE ON public.bulletins_paie FOR EACH ROW EXECUTE FUNCTION fn_protect_bulletin_paie_immutability();
CREATE TRIGGER trg_bp_no_delete BEFORE DELETE ON public.bulletins_paie FOR EACH ROW EXECUTE FUNCTION fn_block_bulletin_paie_delete();
CREATE TRIGGER trg_award_badges_match AFTER UPDATE ON public.candidatures FOR EACH ROW EXECUTE FUNCTION fn_award_badges_match();
CREATE TRIGGER trg_candidature_acceptee_chat AFTER UPDATE OF statut ON public.candidatures FOR EACH ROW WHEN (((new.statut = 'ACCEPTEE'::text) AND ((old.statut IS NULL) OR (old.statut <> 'ACCEPTEE'::text)))) EXECUTE FUNCTION tg_candidature_acceptee_creer_conversation();
CREATE TRIGGER trg_candidature_conflit_planning BEFORE INSERT ON public.candidatures FOR EACH ROW EXECUTE FUNCTION fn_trg_candidature_conflit_planning();
CREATE TRIGGER trg_protect_candidature_statut BEFORE UPDATE ON public.candidatures FOR EACH ROW EXECUTE FUNCTION fn_protect_candidature_statut();
CREATE TRIGGER trg_recompute_score_urgence AFTER INSERT OR UPDATE ON public.candidatures FOR EACH ROW EXECUTE FUNCTION fn_trg_recompute_score_urgence();
CREATE TRIGGER trg_set_candidature_acceptee_a BEFORE UPDATE OF statut ON public.candidatures FOR EACH ROW EXECUTE FUNCTION dec_set_candidature_acceptee_a();
CREATE TRIGGER trg_verifier_profession_etudiant BEFORE INSERT ON public.candidatures FOR EACH ROW EXECUTE FUNCTION dec_verifier_profession_etudiant();
CREATE TRIGGER dec_proteger_signature_contrat BEFORE UPDATE ON public.contrats_mission FOR EACH ROW EXECUTE FUNCTION dec_proteger_signature_contrat();
CREATE TRIGGER dec_xss_contrat BEFORE INSERT OR UPDATE ON public.contrats_mission FOR EACH ROW EXECUTE FUNCTION dec_sanitiser_contrat();
CREATE TRIGGER trg_auto_partager_rib AFTER UPDATE OF statut ON public.contrats_mission FOR EACH ROW WHEN (((new.statut = 'SIGNE_COMPLET'::text) AND (new.type_contrat = 'CDDU'::text))) EXECUTE FUNCTION dec_auto_partager_rib();
CREATE TRIGGER trg_creer_partage_rib_contrat AFTER UPDATE ON public.contrats_mission FOR EACH ROW EXECUTE FUNCTION dec_creer_partage_rib_contrat();
CREATE TRIGGER trg_dec_auto_generer_qr_mission AFTER UPDATE OF statut ON public.contrats_mission FOR EACH ROW EXECUTE FUNCTION dec_auto_generer_qr_mission();
CREATE TRIGGER trg_dec_email_contrat_a_signer AFTER INSERT ON public.contrats_mission FOR EACH ROW EXECUTE FUNCTION dec_email_contrat_a_signer();
CREATE TRIGGER trg_dec_email_contrat_signe_complet AFTER UPDATE OF statut ON public.contrats_mission FOR EACH ROW EXECUTE FUNCTION dec_email_contrat_signe_complet();
CREATE TRIGGER trg_dec_notif_signature_soignant_recue AFTER UPDATE OF signature_soignant ON public.contrats_mission FOR EACH ROW EXECUTE FUNCTION dec_notif_signature_soignant_recue();
CREATE TRIGGER trg_dec_push_contrat_a_signer AFTER INSERT ON public.contrats_mission FOR EACH ROW EXECUTE FUNCTION dec_push_contrat_a_signer();
CREATE TRIGGER trg_dec_push_contrat_signe_complet AFTER UPDATE OF statut ON public.contrats_mission FOR EACH ROW EXECUTE FUNCTION dec_push_contrat_signe_complet();
CREATE TRIGGER trg_protect_contrat_integrity BEFORE UPDATE ON public.contrats_mission FOR EACH ROW EXECUTE FUNCTION fn_protect_contrat_integrity();
CREATE TRIGGER dec_proteger_valid_docs BEFORE UPDATE ON public.documents_soignants FOR EACH ROW EXECUTE FUNCTION dec_proteger_validation_documents();
CREATE TRIGGER trg_bloquer_delete_doc_verifie BEFORE DELETE ON public.documents_soignants FOR EACH ROW EXECUTE FUNCTION fn_bloquer_delete_doc_verifie();
CREATE TRIGGER trg_check_coherence_doc_identite AFTER UPDATE OF statut_verification ON public.documents_soignants FOR EACH ROW WHEN (((new.statut_verification = 'VERIFIE'::statut_verification) AND (new.type_document = 'CARTE_IDENTITE'::type_document))) EXECUTE FUNCTION dec_check_coherence_apres_doc_identite();
CREATE TRIGGER trg_proteger_document_verification BEFORE UPDATE ON public.documents_soignants FOR EACH ROW EXECUTE FUNCTION fn_proteger_document_verification();
CREATE TRIGGER trg_recalculer_docs_valides AFTER INSERT OR DELETE OR UPDATE ON public.documents_soignants FOR EACH ROW EXECUTE FUNCTION fn_recalculer_tous_documents_valides();
CREATE TRIGGER dec_couleur_theme BEFORE INSERT OR UPDATE ON public.etablissements FOR EACH ROW EXECUTE FUNCTION dec_valider_couleur_theme();
CREATE TRIGGER dec_secteur_public_etab BEFORE INSERT OR UPDATE OF type, siret_categorie_juridique ON public.etablissements FOR EACH ROW EXECUTE FUNCTION dec_detecter_secteur_public_etablissement();
CREATE TRIGGER trg_anonymiser_notations_etab_supprime AFTER UPDATE OF supprime_le ON public.etablissements FOR EACH ROW EXECUTE FUNCTION fn_trg_anonymiser_notations_suppression();
CREATE TRIGGER trg_auto_code_parrainage_etab BEFORE INSERT ON public.etablissements FOR EACH ROW EXECUTE FUNCTION fn_auto_code_parrainage_etab();
CREATE TRIGGER trg_auto_valider_etablissement BEFORE UPDATE ON public.etablissements FOR EACH ROW EXECUTE FUNCTION fn_auto_valider_etablissement_siret();
CREATE TRIGGER trg_classifier_acquisition_etab BEFORE INSERT ON public.etablissements FOR EACH ROW EXECUTE FUNCTION fn_trg_classifier_acquisition();
CREATE TRIGGER trg_init_prefs_etab AFTER INSERT ON public.etablissements FOR EACH ROW EXECUTE FUNCTION fn_trg_init_preferences_notifications();
CREATE TRIGGER trg_protect_etablissement_commercial BEFORE UPDATE ON public.etablissements FOR EACH ROW EXECUTE FUNCTION fn_protect_etablissement_commercial();
CREATE TRIGGER trg_verifier_coherence_publication BEFORE INSERT OR UPDATE ON public.etablissements FOR EACH ROW EXECUTE FUNCTION fn_verifier_coherence_publication();
CREATE TRIGGER dec_auto_eval BEFORE INSERT ON public.evaluations FOR EACH ROW EXECUTE FUNCTION dec_refuser_auto_evaluation();
CREATE TRIGGER dec_verifier_eval BEFORE INSERT ON public.evaluations FOR EACH ROW EXECUTE FUNCTION dec_verifier_evaluation_counterparty();
CREATE TRIGGER trg_auto_publier_evaluation BEFORE INSERT ON public.evaluations FOR EACH ROW EXECUTE FUNCTION fn_auto_publier_evaluation();
CREATE TRIGGER trg_email_evaluation AFTER INSERT ON public.evaluations FOR EACH ROW EXECUTE FUNCTION fn_trg_email_evaluation();
CREATE TRIGGER trg_evaluer_dans_delai BEFORE INSERT ON public.evaluations FOR EACH ROW EXECUTE FUNCTION dec_evaluer_dans_delai();
CREATE TRIGGER trg_maj_note_moyenne AFTER INSERT OR UPDATE ON public.evaluations FOR EACH ROW EXECUTE FUNCTION dec_maj_note_moyenne();
CREATE TRIGGER trg_maj_note_moyenne_etab AFTER INSERT ON public.evaluations FOR EACH ROW WHEN ((new.type_evaluateur = 'SOIGNANT'::text)) EXECUTE FUNCTION dec_maj_note_moyenne_etab();
CREATE TRIGGER trg_factor_advances_modifie_le BEFORE UPDATE ON public.factor_advances FOR EACH ROW EXECUTE FUNCTION fn_factor_advances_modifie_le();
CREATE TRIGGER dec_bloquer_paiement_manuel BEFORE UPDATE ON public.factures FOR EACH ROW EXECUTE FUNCTION dec_bloquer_paiement_manuel_facture();
CREATE TRIGGER dec_idempotence_facture BEFORE UPDATE ON public.factures FOR EACH ROW EXECUTE FUNCTION dec_idempotence_facture_payee();
CREATE TRIGGER dec_num_facture BEFORE INSERT ON public.factures FOR EACH ROW EXECUTE FUNCTION dec_verifier_numerotation_facture();
CREATE TRIGGER dec_proprio_facture BEFORE UPDATE ON public.factures FOR EACH ROW EXECUTE FUNCTION dec_bloquer_changement_proprio_facture();
CREATE TRIGGER dec_secteur_public_facture BEFORE INSERT ON public.factures FOR EACH ROW EXECUTE FUNCTION dec_detecter_secteur_public_facture();
CREATE TRIGGER dec_valider_paiement BEFORE UPDATE ON public.factures FOR EACH ROW EXECUTE FUNCTION dec_valider_paiement_facture();
CREATE TRIGGER trg_parrainage_commission_encaissee AFTER INSERT OR UPDATE OF statut ON public.factures FOR EACH ROW EXECUTE FUNCTION fn_trg_parrainage_commission_encaissee();
CREATE TRIGGER trg_protect_facture_montants BEFORE UPDATE ON public.factures FOR EACH ROW EXECUTE FUNCTION fn_protect_facture_montants();
CREATE TRIGGER trg_valider_parrainage_etab_commission AFTER INSERT OR UPDATE ON public.factures FOR EACH ROW EXECUTE FUNCTION fn_trg_valider_parrainage_etab_commission();
CREATE TRIGGER trg_anti_seed_facture_honoraire BEFORE INSERT ON public.factures_honoraires FOR EACH ROW EXECUTE FUNCTION fn_anti_seed_facture_honoraire();
CREATE TRIGGER trg_defacto_auto_cession AFTER UPDATE OF statut ON public.factures_honoraires FOR EACH ROW EXECUTE FUNCTION fn_trg_defacto_auto_cession();
CREATE TRIGGER trg_fh_auto_audit_insert AFTER INSERT ON public.factures_honoraires FOR EACH ROW EXECUTE FUNCTION fn_fh_auto_audit();
CREATE TRIGGER trg_fh_auto_audit_update AFTER UPDATE ON public.factures_honoraires FOR EACH ROW EXECUTE FUNCTION fn_fh_auto_audit();
CREATE TRIGGER trg_fh_detect_public BEFORE INSERT ON public.factures_honoraires FOR EACH ROW EXECUTE FUNCTION fn_fh_detect_public_sector();
CREATE TRIGGER trg_fh_immutability BEFORE UPDATE ON public.factures_honoraires FOR EACH ROW EXECUTE FUNCTION fn_protect_facture_honoraire_immutability();
CREATE TRIGGER trg_fh_updated_at BEFORE UPDATE ON public.factures_honoraires FOR EACH ROW EXECUTE FUNCTION fn_fh_updated_at();
CREATE TRIGGER trg_maj_tresorerie_bloquee AFTER INSERT OR UPDATE OF montant_ht, montant_ttc, statut_litige, litige_id ON public.factures_honoraires FOR EACH ROW EXECUTE FUNCTION trg_fn_maj_tresorerie_bloquee();
CREATE TRIGGER trg_notif_admin_remboursement_manuel AFTER INSERT OR UPDATE OF mode_remboursement, type_document ON public.factures_honoraires FOR EACH ROW EXECUTE FUNCTION fn_trg_notif_admin_remboursement_manuel();
CREATE TRIGGER trg_parrainage_gmv_encaisse AFTER INSERT OR UPDATE OF statut ON public.factures_honoraires FOR EACH ROW EXECUTE FUNCTION fn_trg_parrainage_gmv_encaisse();
CREATE TRIGGER trg_fs_updated_at BEFORE UPDATE ON public.filtres_sauvegardes FOR EACH ROW EXECUTE FUNCTION fn_trg_pn_updated_at();
CREATE TRIGGER trg_heures_externes_maj BEFORE UPDATE ON public.heures_externes_soignants FOR EACH ROW EXECUTE FUNCTION fn_set_mis_a_jour_le();
CREATE TRIGGER trg_email_invitation_equipe_etab AFTER INSERT ON public.invitations_etablissement FOR EACH ROW EXECUTE FUNCTION dec_email_invitation_equipe_etab();
CREATE TRIGGER trg_ial_no_delete BEFORE DELETE ON public.invoice_audit_log FOR EACH ROW EXECUTE FUNCTION fn_block_audit_log_delete();
CREATE TRIGGER trg_ial_no_update BEFORE UPDATE ON public.invoice_audit_log FOR EACH ROW EXECUTE FUNCTION fn_block_audit_log_update();
CREATE TRIGGER dec_audit_immuable BEFORE DELETE OR UPDATE ON public.journaux_audit FOR EACH ROW EXECUTE FUNCTION dec_proteger_journaux_audit();
CREATE TRIGGER dec_proteger_audit_delete BEFORE DELETE ON public.journaux_audit FOR EACH ROW EXECUTE FUNCTION dec_bloquer_suppression_audit();
CREATE TRIGGER dec_proteger_audit_update BEFORE UPDATE ON public.journaux_audit FOR EACH ROW EXECUTE FUNCTION dec_bloquer_modification_audit();
CREATE TRIGGER dec_limite_liste BEFORE INSERT ON public.liste_attente_premium FOR EACH ROW EXECUTE FUNCTION dec_limiter_liste_attente();
CREATE TRIGGER dec_litige_48h BEFORE INSERT ON public.litiges FOR EACH ROW EXECUTE FUNCTION dec_contestation_48h();
CREATE TRIGGER dec_proteger_litige BEFORE UPDATE ON public.litiges FOR EACH ROW EXECUTE FUNCTION dec_proteger_resolution_litige();
CREATE TRIGGER trg_litige_accord_mutuel BEFORE UPDATE OF accord_soignant_le, accord_etablissement_le ON public.litiges FOR EACH ROW EXECUTE FUNCTION fn_trg_litige_accord_mutuel();
CREATE TRIGGER trg_litige_gel_degel_facture AFTER INSERT OR UPDATE OF statut ON public.litiges FOR EACH ROW EXECUTE FUNCTION fn_trg_litige_gel_degel_facture();
CREATE TRIGGER trg_litige_mapping_categorie BEFORE INSERT OR UPDATE OF type_litige ON public.litiges FOR EACH ROW EXECUTE FUNCTION fn_trg_litige_mapping_categorie();
CREATE TRIGGER trg_litige_notify_support AFTER INSERT ON public.litiges FOR EACH ROW EXECUTE FUNCTION fn_trg_litige_notify_support();
CREATE TRIGGER trg_litige_reponse_auto_statut BEFORE UPDATE ON public.litiges FOR EACH ROW EXECUTE FUNCTION dec_litige_reponse_auto_statut();
CREATE TRIGGER trg_notifier_creation_litige AFTER INSERT ON public.litiges FOR EACH ROW EXECUTE FUNCTION dec_notifier_creation_litige();
CREATE TRIGGER trg_notifier_reponse_litige AFTER UPDATE ON public.litiges FOR EACH ROW EXECUTE FUNCTION dec_notifier_reponse_litige();
CREATE TRIGGER trg_notifier_resolution_litige AFTER UPDATE ON public.litiges FOR EACH ROW EXECUTE FUNCTION dec_notifier_resolution_litige();
CREATE TRIGGER trg_recalcul_score_v2_litiges AFTER UPDATE OF statut ON public.litiges FOR EACH ROW EXECUTE FUNCTION fn_trg_recalculer_score_v2();
CREATE TRIGGER trg_protect_message_chat BEFORE UPDATE ON public.messages_chat FOR EACH ROW EXECUTE FUNCTION fn_protect_message_chat_update();
CREATE TRIGGER trg_notifier_nouveau_message AFTER INSERT ON public.messages_mission FOR EACH ROW EXECUTE FUNCTION dec_notifier_nouveau_message();
CREATE TRIGGER trg_protect_message_mission BEFORE UPDATE ON public.messages_mission FOR EACH ROW EXECUTE FUNCTION fn_protect_message_mission_update();
CREATE TRIGGER trg_no_overlap_creneaux BEFORE INSERT OR UPDATE ON public.mission_creneaux FOR EACH ROW EXECUTE FUNCTION fn_no_overlap_creneaux();
CREATE TRIGGER trg_protect_creneaux_facture BEFORE INSERT OR DELETE OR UPDATE ON public.mission_creneaux FOR EACH ROW EXECUTE FUNCTION fn_protect_creneaux_si_facture();
CREATE TRIGGER trg_sync_creneaux AFTER INSERT OR DELETE OR UPDATE ON public.mission_creneaux FOR EACH ROW EXECUTE FUNCTION fn_sync_mission_creneaux();
CREATE TRIGGER dec_annuler_contrat AFTER UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_annuler_contrat_si_mission_annulee();
CREATE TRIGGER dec_anti_double BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_anti_double_assignation();
CREATE TRIGGER dec_bloquer_modif_acceptee BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_bloquer_modif_apres_acceptation();
CREATE TRIGGER dec_bonus_urgence AFTER UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_bonus_urgence();
CREATE TRIGGER dec_chevauchement BEFORE INSERT OR UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_refuser_chevauchement_soignant();
CREATE TRIGGER dec_codes_pointage BEFORE INSERT ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_generer_codes_pointage();
CREATE TRIGGER dec_docs_fin_mission BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_verifier_docs_jusqua_fin();
CREATE TRIGGER dec_eligibilite_liberal BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_verifier_eligibilite_liberal();
CREATE TRIGGER dec_facture_impayee BEFORE INSERT ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_bloquer_si_facture_impayee();
CREATE TRIGGER dec_heures_plateforme AFTER INSERT OR UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_incrementer_heures_plateforme();
CREATE TRIGGER dec_maj_compteurs AFTER UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_maj_compteurs_soignant();
CREATE TRIGGER dec_mission_commission BEFORE INSERT OR UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_calculer_commission();
CREATE TRIGGER dec_mission_liberee BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_alerte_mission_liberee();
CREATE TRIGGER dec_mission_maj_fiabilite AFTER UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_mettre_a_jour_fiabilite();
CREATE TRIGGER dec_mission_passee BEFORE INSERT ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_refuser_mission_passee();
CREATE TRIGGER dec_mission_plafond_48h_after_insert AFTER INSERT ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_verifier_plafond_48h();
CREATE TRIGGER dec_mission_plafond_48h_before_update BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_verifier_plafond_48h();
CREATE TRIGGER dec_mission_plafond_rist BEFORE INSERT OR UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_appliquer_plafond_rist();
CREATE TRIGGER dec_mission_repos_11h_after_insert AFTER INSERT ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_verifier_repos_11h();
CREATE TRIGGER dec_mission_repos_11h_before_update BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_verifier_repos_11h();
CREATE TRIGGER dec_mission_z_finance BEFORE INSERT OR UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_calculer_finance_mission();
CREATE TRIGGER dec_net_estime BEFORE INSERT OR UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_calculer_net_estime();
CREATE TRIGGER dec_notif_mission AFTER INSERT OR UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_notifier_changement_mission();
CREATE TRIGGER dec_penalite_annulation BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_penalite_annulation_tardive();
CREATE TRIGGER dec_premiere_mission AFTER UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_premiere_mission();
CREATE TRIGGER dec_profession_etab BEFORE INSERT ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_verifier_profession_etablissement();
CREATE TRIGGER dec_proteger_mission_soignant BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_proteger_mission_soignant();
CREATE TRIGGER dec_type_contrat_compat BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_verifier_type_contrat_mission();
CREATE TRIGGER dec_type_paiement_mission BEFORE INSERT OR UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_definir_type_paiement();
CREATE TRIGGER trg_absence_event_score AFTER UPDATE OF absence_sans_prevenir ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_absence_event_score();
CREATE TRIGGER trg_annuler_contrat_orphelin AFTER UPDATE OF soignant_assigne_id ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_annuler_contrat_orphelin();
CREATE TRIGGER trg_anti_seed_mission BEFORE INSERT ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_anti_seed_mission();
CREATE TRIGGER trg_auto_commission_facturee BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_auto_commission_facturee();
CREATE TRIGGER trg_auto_cotisations AFTER UPDATE OF statut ON public.missions FOR EACH ROW WHEN ((new.statut = 'TERMINEE'::statut_mission)) EXECUTE FUNCTION dec_auto_calculer_cotisations();
CREATE TRIGGER trg_auto_creer_bulletin_paie AFTER UPDATE OF statut ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_auto_creer_bulletin_paie_trg();
CREATE TRIGGER trg_auto_facture_honoraires AFTER UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_auto_facture_honoraires();
CREATE TRIGGER trg_auto_heures_majorees BEFORE INSERT OR UPDATE OF debut_le, fin_le, duree_heures ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_auto_heures_majorees();
CREATE TRIGGER trg_auto_notify_mission_urgente AFTER INSERT OR UPDATE OF est_urgente, statut, soignant_assigne_id ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_auto_notify_mission_urgente();
CREATE TRIGGER trg_calculer_financier BEFORE INSERT OR UPDATE OF taux_horaire_base, duree_heures, debut_le, fin_le, heures_nuit, heures_dimanche, heures_ferie, taux_ifm, taux_icp ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_calculer_financier_mission();
CREATE TRIGGER trg_coherence_statut_soignant BEFORE INSERT OR UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_coherence_statut_soignant();
CREATE TRIGGER trg_compteur_absences_sans_prevenir AFTER INSERT OR UPDATE OF statut, absence_sans_prevenir ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_compteur_absences_sans_prevenir();
CREATE TRIGGER trg_conversation_assignation AFTER UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_creer_conversation_assignation();
CREATE TRIGGER trg_dec_valider_compatibilite_mission_liberal BEFORE INSERT OR UPDATE OF type_contrat_recherche, profession_requise, etablissement_id ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_valider_compatibilite_mission_liberal();
CREATE TRIGGER trg_dec_verifier_moyenne_44h_after_insert AFTER INSERT ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_verifier_moyenne_44h_12_semaines();
CREATE TRIGGER trg_dec_verifier_moyenne_44h_before_update BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_verifier_moyenne_44h_12_semaines();
CREATE TRIGGER trg_dec_verifier_repos_hebdo_35h_after_insert AFTER INSERT ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_verifier_repos_hebdo_35h();
CREATE TRIGGER trg_dec_verifier_repos_hebdo_35h_before_update BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_verifier_repos_hebdo_35h();
CREATE TRIGGER trg_desistement_garanti AFTER UPDATE OF statut ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_desistement_garanti();
CREATE TRIGGER trg_email_mission_terminee AFTER UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_email_mission_terminee();
CREATE TRIGGER trg_favori_nouvelle_mission AFTER INSERT ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_favori_nouvelle_mission();
CREATE TRIGGER trg_protect_mission_financials BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_protect_mission_financials();
CREATE TRIGGER trg_rappel_evaluation AFTER UPDATE OF statut ON public.missions FOR EACH ROW WHEN ((new.statut = 'TERMINEE'::statut_mission)) EXECUTE FUNCTION dec_rappel_evaluation();
CREATE TRIGGER trg_recalcul_score_v2_missions AFTER UPDATE OF statut ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_recalculer_score_v2();
CREATE TRIGGER trg_sms_annulation_tardive AFTER UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_sms_annulation_tardive();
CREATE TRIGGER trg_valider_parrainage_soignant AFTER UPDATE OF statut ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_valider_parrainage_soignant_premiere_mission();
CREATE TRIGGER trg_valider_transition_statut BEFORE UPDATE OF statut ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_valider_transition_statut_mission();
CREATE TRIGGER trg_valider_type_contrat_mission BEFORE INSERT OR UPDATE OF type_contrat_recherche, profession_requise ON public.missions FOR EACH ROW EXECUTE FUNCTION dec_valider_type_contrat_mission();
CREATE TRIGGER trg_verifier_docs_avant_debut BEFORE UPDATE OF statut ON public.missions FOR EACH ROW WHEN (((new.statut = 'EN_COURS'::statut_mission) AND (old.statut = 'ASSIGNEE'::statut_mission))) EXECUTE FUNCTION dec_verifier_docs_avant_debut();
CREATE TRIGGER trg_verifier_mandat_avant_debut BEFORE UPDATE OF statut ON public.missions FOR EACH ROW WHEN (((new.statut = 'EN_COURS'::statut_mission) AND (old.statut = 'ASSIGNEE'::statut_mission))) EXECUTE FUNCTION fn_trg_verifier_mandat_avant_debut();
CREATE TRIGGER trg_verifier_onboarding_etab BEFORE INSERT ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_trg_verifier_onboarding_etab();
CREATE TRIGGER trg_zz_geler_mission BEFORE UPDATE ON public.missions FOR EACH ROW EXECUTE FUNCTION fn_geler_mission_a_assignation();
CREATE TRIGGER trg_recalcul_score_v2_notations AFTER INSERT OR UPDATE OF critere_1, critere_2, critere_3, critere_4, masque ON public.notations_missions FOR EACH ROW EXECUTE FUNCTION fn_trg_recalculer_score_v2();
CREATE TRIGGER dec_proteger_notif BEFORE UPDATE ON public.notifications FOR EACH ROW EXECUTE FUNCTION dec_proteger_contenu_notification();
CREATE TRIGGER trg_protect_notification_update BEFORE UPDATE ON public.notifications FOR EACH ROW WHEN ((NOT est_admin())) EXECUTE FUNCTION fn_protect_notification_update();
CREATE TRIGGER trg_protect_paiement_mission BEFORE UPDATE ON public.paiements_mission FOR EACH ROW EXECUTE FUNCTION fn_protect_paiement_mission();
CREATE TRIGGER trg_bp_passage_paye AFTER UPDATE ON public.paiements_soignant FOR EACH ROW EXECUTE FUNCTION fn_bp_passage_paye_trg();
CREATE TRIGGER trg_email_paiement_confirme AFTER UPDATE ON public.paiements_soignant FOR EACH ROW EXECUTE FUNCTION fn_trg_email_paiement_confirme();
CREATE TRIGGER trg_protect_paiement_soignant BEFORE UPDATE ON public.paiements_soignant FOR EACH ROW EXECUTE FUNCTION fn_protect_paiement_soignant();
CREATE TRIGGER trg_parcours_liberal_maj BEFORE UPDATE ON public.parcours_liberal_soignants FOR EACH ROW EXECUTE FUNCTION fn_set_mis_a_jour_le();
CREATE TRIGGER trg_pn_updated_at BEFORE UPDATE ON public.preferences_notifications FOR EACH ROW EXECUTE FUNCTION fn_trg_pn_updated_at();
CREATE TRIGGER trg_pnpe_updated_at BEFORE UPDATE ON public.preferences_notifications_par_evenement FOR EACH ROW EXECUTE FUNCTION fn_trg_pn_updated_at();
CREATE TRIGGER dec_depart_arrivee BEFORE INSERT OR UPDATE ON public.presences FOR EACH ROW EXECUTE FUNCTION dec_depart_apres_arrivee();
CREATE TRIGGER dec_fenetre_pointage BEFORE INSERT ON public.presences FOR EACH ROW EXECUTE FUNCTION dec_fenetre_pointage();
CREATE TRIGGER dec_presence_antifraude BEFORE INSERT OR UPDATE ON public.presences FOR EACH ROW EXECUTE FUNCTION dec_antifraude_presence();
CREATE TRIGGER dec_proteger_presence_soignant BEFORE UPDATE ON public.presences FOR EACH ROW EXECUTE FUNCTION dec_proteger_presence_soignant();
CREATE TRIGGER trg_alerte_pause_obligatoire BEFORE UPDATE ON public.presences FOR EACH ROW WHEN (((new.pointage_depart_le IS NOT NULL) AND (new.duree_brute_min IS NOT NULL))) EXECUTE FUNCTION dec_alerte_pause_obligatoire();
CREATE TRIGGER trg_calculer_duree BEFORE INSERT OR UPDATE ON public.presences FOR EACH ROW WHEN ((new.pointage_depart_le IS NOT NULL)) EXECUTE FUNCTION dec_calculer_duree_presence();
CREATE TRIGGER trg_protect_presence_integrity BEFORE UPDATE ON public.presences FOR EACH ROW EXECUTE FUNCTION fn_protect_presence_integrity();
CREATE TRIGGER trg_see_updated_at BEFORE UPDATE ON public.serie_email_envois FOR EACH ROW EXECUTE FUNCTION fn_trg_pn_updated_at();
CREATE TRIGGER dec_age_minimum BEFORE INSERT OR UPDATE ON public.soignants FOR EACH ROW EXECUTE FUNCTION dec_verifier_age_minimum();
CREATE TRIGGER dec_bloquer_desinscrip BEFORE UPDATE ON public.soignants FOR EACH ROW EXECUTE FUNCTION dec_bloquer_desinscription_missions();
CREATE TRIGGER trg_anonymiser_notations_soignant_supprime AFTER UPDATE OF supprime_le ON public.soignants FOR EACH ROW EXECUTE FUNCTION fn_trg_anonymiser_notations_suppression();
CREATE TRIGGER trg_auto_code_parrainage BEFORE INSERT ON public.soignants FOR EACH ROW EXECUTE FUNCTION fn_auto_code_parrainage();
CREATE TRIGGER trg_check_coherence_rpps AFTER UPDATE OF rpps_verifie ON public.soignants FOR EACH ROW WHEN ((new.rpps_verifie = true)) EXECUTE FUNCTION dec_check_coherence_apres_rpps();
CREATE TRIGGER trg_classifier_acquisition_soignant BEFORE INSERT ON public.soignants FOR EACH ROW EXECUTE FUNCTION fn_trg_classifier_acquisition();
CREATE TRIGGER trg_init_prefs_soignant AFTER INSERT ON public.soignants FOR EACH ROW EXECUTE FUNCTION fn_trg_init_preferences_notifications();
CREATE TRIGGER trg_protect_soignant_verification BEFORE UPDATE ON public.soignants FOR EACH ROW EXECUTE FUNCTION fn_protect_soignant_verification();
CREATE TRIGGER trg_recalcul_badge_ambassadeur AFTER UPDATE OF supprime_le, statut_compte ON public.soignants FOR EACH ROW EXECUTE FUNCTION fn_trg_recalcul_badge_ambassadeur();
CREATE TRIGGER trg_sync_types_contrat BEFORE UPDATE ON public.soignants FOR EACH ROW EXECUTE FUNCTION dec_sync_types_contrat_exercice();
CREATE TRIGGER trg_valider_type_exercice_soignant BEFORE INSERT OR UPDATE OF type_exercice, profession ON public.soignants FOR EACH ROW EXECUTE FUNCTION dec_valider_type_exercice_soignant();
CREATE TRIGGER trg_verifier_type_exercice BEFORE INSERT OR UPDATE ON public.soignants FOR EACH ROW EXECUTE FUNCTION dec_verifier_type_exercice_profession();
CREATE TRIGGER trg_protect_stripe_connect BEFORE UPDATE ON public.stripe_connect_onboarding FOR EACH ROW EXECUTE FUNCTION fn_protect_stripe_connect_onboarding();
CREATE TRIGGER trg_propage_stripe_payment_intent AFTER INSERT OR UPDATE OF stripe_payment_intent_id, mission_id ON public.stripe_transfers FOR EACH ROW EXECUTE FUNCTION fn_propage_stripe_payment_intent_trg();
CREATE TRIGGER trg_protect_stripe_transfer BEFORE UPDATE ON public.stripe_transfers FOR EACH ROW EXECUTE FUNCTION fn_protect_stripe_transfer();
CREATE TRIGGER trg_award_badges_swipe AFTER INSERT ON public.swipes FOR EACH ROW EXECUTE FUNCTION fn_award_badges_swipe();
CREATE TRIGGER trg_update_streak_on_swipe AFTER INSERT ON public.swipes FOR EACH ROW EXECUTE FUNCTION fn_update_streak_on_swipe();
CREATE TRIGGER dec_xss_template BEFORE INSERT OR UPDATE ON public.templates_contrat FOR EACH ROW EXECUTE FUNCTION dec_sanitiser_contrat();
