-- Sprint 17-A PR 1 — Parrainage soignant : prime cash 50€+50€
--
-- Étend le schéma existant (table parrainages, code_parrainage sur soignants)
-- pour supporter le moteur cash :
--   - Nouveaux statuts : FILLEUL_ACTIF, VALIDE_EN_ATTENTE_SEUIL, PRIME_VERSEE, FRAUDE
--   - Colonnes de suivi : commission_cumulee_filleul, filleul_active_le, prime_versee_le
--   - Table parrainage_fraude_signals pour traçabilité anti-fraude
--
-- Existant préservé :
--   - soignants.code_parrainage (JO-XXXXXX, trigger auto-insert)
--   - soignants.badge_ambassadeur, parrainages.bonus_heures_*
--   - fn_generer_code_parrainage, fn_appliquer_parrainage, fn_mes_filleuls
--   - trg_valider_parrainage_soignant (sera remplacé PR 3 pour ajouter seuil commission)

-- 1) Étendre CHECK constraint statut pour les nouveaux états
ALTER TABLE public.parrainages DROP CONSTRAINT IF EXISTS parrainages_statut_check;
ALTER TABLE public.parrainages ADD CONSTRAINT parrainages_statut_check
  CHECK (statut IN (
    'EN_ATTENTE',
    'FILLEUL_ACTIF',
    'VALIDE_EN_ATTENTE_SEUIL',
    'PRIME_VERSEE',
    'FRAUDE',
    'VALIDE',
    'EXPIRED',
    'ANNULE'
  ));

-- 2) Nouvelles colonnes de suivi prime cash
ALTER TABLE public.parrainages
  ADD COLUMN IF NOT EXISTS commission_cumulee_filleul NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS filleul_active_le TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS prime_versee_le TIMESTAMPTZ;

COMMENT ON COLUMN public.parrainages.commission_cumulee_filleul IS
  'Commission ENCAISSÉE (factures PAYEE) générée par le filleul, cumulée. '
  'Seuil >= 100€ requis pour débloquer la prime cash 50€+50€.';

COMMENT ON COLUMN public.parrainages.filleul_active_le IS
  'Timestamp de la 1ère mission TERMINEE du filleul (condition 2/4 pour la prime).';

COMMENT ON COLUMN public.parrainages.prime_versee_le IS
  'Timestamp du versement effectif de la prime 50€+50€ via worker async.';

-- 3) Table parrainage_fraude_signals
CREATE TABLE IF NOT EXISTS public.parrainage_fraude_signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  parrainage_id UUID NOT NULL REFERENCES public.parrainages(id) ON DELETE CASCADE,
  type TEXT NOT NULL CHECK (type IN ('MEME_IP', 'MEME_DEVICE', 'PATTERN_SUSPECT', 'ADMIN_FLAG')),
  detail JSONB NOT NULL DEFAULT '{}'::jsonb,
  cree_le TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_fraude_signals_parrainage
  ON public.parrainage_fraude_signals(parrainage_id);

ALTER TABLE public.parrainage_fraude_signals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_fraude_signals_admin ON public.parrainage_fraude_signals;
CREATE POLICY pol_fraude_signals_admin ON public.parrainage_fraude_signals
  FOR ALL USING (est_admin());

GRANT SELECT ON public.parrainage_fraude_signals TO authenticated;
GRANT ALL ON public.parrainage_fraude_signals TO service_role;

-- 4) Index pour recherche rapide sur commission tracking
CREATE INDEX IF NOT EXISTS idx_parrainages_statut_filleul
  ON public.parrainages(filleul_id, statut)
  WHERE statut IN ('EN_ATTENTE', 'FILLEUL_ACTIF', 'VALIDE_EN_ATTENTE_SEUIL');

-- 5) Étendre audit CHECK pour nouveaux types d'actions
ALTER TABLE public.journaux_audit DROP CONSTRAINT IF EXISTS journaux_audit_action_check;
ALTER TABLE public.journaux_audit ADD CONSTRAINT journaux_audit_action_check CHECK (action = ANY (ARRAY[
  'INSCRIPTION','CONNEXION','DECONNEXION','MODIFICATION_PROFIL','SUPPRESSION_COMPTE',
  'UPLOAD_DOCUMENT','TELECHARGEMENT_DOCUMENT','VERIFICATION_DOCUMENT','VERIFICATION_RPPS',
  'CREATION_MISSION','MODIFICATION_MISSION','ANNULATION_MISSION','CANDIDATURE','ASSIGNATION',
  'POINTAGE','SIGNATURE_CONTRAT','EVALUATION','PAIEMENT','FACTURATION',
  'DONNEES_PERSO_CONSULTATION','DONNEES_PERSO_EXPORT','DONNEES_PERSO_SUPPRESSION',
  'ADMIN_ACTION','SYSTEM','RIB_CONSULTE','RIB_PARTAGE','CONTRAT_SIGNE',
  'DOCUMENT_CONSULTATION','DOCUMENT_TELEVERSEMENT','DONNEES_PERSO_MODIFICATION',
  'EXPORT_RH_PAIE','FINANCE_FACTURE_PAYEE','MISSION_ASSIGNATION','MISSION_CREATION',
  'RGPD_EXPORT_DONNEES','RGPD_SUPPRESSION_COMPTE','RGPD_SUPPRESSION_COMPTE_ETABLISSEMENT',
  'DEGEL_APPLIED','OVERRIDE_CHAMP_POST_GEL','GEL_APPLIED','OVERRIDE_ANTI_SEED',
  'CONNECT_METADATA_MANQUANTE','DOCUMENT_VERIFICATION_AUTO',
  'FACTURE_COMMISSION_PAYEE_SKIP_ANOMALIE','FACTURE_HONORAIRES_PAYEE_SKIP_ANOMALIE',
  'FINANCE_CHARGE_EXPIRED','FINANCE_CHARGE_FAILED','FINANCE_CHARGE_PENDING',
  'FINANCE_CHARGE_REFUNDED','FINANCE_DISPUTE_CLOSE','FINANCE_DISPUTE_OUVERTE',
  'FINANCE_PAYOUT_CANCELED','FINANCE_PAYOUT_CREATED','FINANCE_PAYOUT_FAILED',
  'FINANCE_PAYOUT_PAID','FINANCE_SEPA_CAPTURE','FINANCE_TRANSFER_CONNECT',
  'FINANCE_TRANSFER_CREATED','FINANCE_TRANSFER_FAILED','FINANCE_TRANSFER_REVERSED',
  'FINANCE_TRANSFER_UPDATED','STRIPE_CHECKOUT_ORPHANED_RECOVERED',
  'STRIPE_CONNECT_ACCOUNT_DELETED','ATTESTATION_SANTE_SIGNEE',
  'EXCLUSION_CREEE','EXCLUSION_SUPPRIMEE','FACTURE_GENEREE',
  'MISSION_ANNULATION_SERIE','MISSION_MODIFICATION','PAIEMENT_SOIGNANT_DECLARE_ETAB',
  'RECLAMATION_CREEE','ADMIN_CONSULTATION_ETABLISSEMENT','ADMIN_CONSULTATION_SOIGNANT',
  'DOCUMENT_SUPPRESSION','HEURES_EXTERNES_DECLAREES','MISSION_ANNULATION',
  'NOTE_HONORAIRES_GENEREE','PRESENCE_CONTESTATION','PRESENCE_POINTAGE_ARRIVEE',
  'PRESENCE_VALIDATION','PRESENCE_VALIDATION_LOT','RGPD_CONSENTEMENT_DONNE',
  'PAIEMENT_MONTANT_ECART','FACTURE_COMMISSION_CREATED_VIA_STRIPE',
  'TAUX_COMMISSION_MODIFIE','LITIGE_GEL_SCOPE_MODIFIE','PREFERENCE_NOTIFICATION_MODIFIEE',
  'NOTIFICATION_SKIPPED','SERIE_EMAIL_ENVOYE','SERIE_EMAIL_SKIPPED',
  'FILTRE_CREE','FILTRE_MODIFIE','FILTRE_SUPPRIME',
  'ALERTE_ACTIVEE','ALERTE_DESACTIVEE','ALERTE_ENVOYEE',
  'POOL_URGENCE_NOTIFICATIONS_ENVOYEES','POOL_URGENCE_ACCEPTATION_RAPIDE',
  'POOL_URGENCE_VALIDATION_ETAB','POOL_URGENCE_REFUS_ETAB','POOL_URGENCE_SMS_TOGGLE',
  'FAVORI_AJOUTE','FAVORI_RETIRE','SCORE_FIABILITE_PENALITE_LITIGE',
  'PARRAINAGE_ETAB_APPLIQUE','PARRAINAGE_ETAB_VALIDE','CREDIT_PARRAINAGE_CREE',
  'CREDIT_PARRAINAGE_APPLIQUE','PARRAINAGE_ETAB_ANOMALIE',
  'PARRAINAGE_SOIGNANT_FILLEUL_ACTIF','PARRAINAGE_SOIGNANT_SEUIL_ATTEINT',
  'PARRAINAGE_SOIGNANT_PRIME_VERSEE','PARRAINAGE_SOIGNANT_FRAUDE',
  'INSCRIPTION_LISTE_ATTENTE_PREVOYANCE','SCORE_RECALCULE_V2'
]));

-- 6) Étendre notifications CHECK pour PARRAINAGE_PRIME
ALTER TABLE public.notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE public.notifications ADD CONSTRAINT notifications_type_check CHECK (type = ANY (ARRAY[
  'CANDIDATURE_ACCEPTEE','CANDIDATURE_REFUSEE','CANDIDATURE_PROPOSEE',
  'MISSION_ACCEPTEE','MISSION_ANNULEE','MISSION_TERMINEE','MISSION_URGENTE','MISSION_NON_POURVUE','MISSION_ASSIGNEE',
  'CONTRAT_A_SIGNER','CONTRAT_SIGNE','FACTURE_EMISE','FACTURE_PAYEE',
  'DOCUMENT_EXPIRANT','RAPPEL_DOCUMENTS','DOCUMENT_VERIFIE','DOCUMENT_REJETE',
  'MESSAGE_RECU','MESSAGE_ADMIN','POINTAGE_ARRIVEE','POINTAGE_DEPART','EVALUATION_RECUE','PARRAINAGE',
  'RAPPEL_MISSION','POOL_URGENCE','POOL_URGENCE_ACCEPTATION','SYSTEM',
  'LITIGE_OUVERT','LITIGE_REPONSE','LITIGE_RESOLU','LITIGE_MEDIATION',
  'CHORUS_DEPOSEE','CHORUS_MISE_A_DISPOSITION','CHORUS_PAIEMENT_EN_COURS','CHORUS_PAIEMENT_COMPTABILISE','CHORUS_REJETEE',
  'FAVORI_NOUVELLE_MISSION','CREDIT_PARRAINAGE',
  'PARRAINAGE_PRIME_VERSEE'
]));

NOTIFY pgrst, 'reload schema';
