-- Phase 2 Option Y — étendre CHECK journaux_audit_action_check pour accueillir
-- l'action FACTURE_COMMISSION_CREATED_VIA_STRIPE (webhook stripe Option Y
-- émet une facture commission PAYEE directement après capture à la source).

ALTER TABLE public.journaux_audit DROP CONSTRAINT IF EXISTS journaux_audit_action_check;

ALTER TABLE public.journaux_audit ADD CONSTRAINT journaux_audit_action_check CHECK (
    action = ANY (ARRAY[
        'INSCRIPTION','CONNEXION','DECONNEXION','MODIFICATION_PROFIL','SUPPRESSION_COMPTE',
        'UPLOAD_DOCUMENT','TELECHARGEMENT_DOCUMENT','VERIFICATION_DOCUMENT','VERIFICATION_RPPS',
        'CREATION_MISSION','MODIFICATION_MISSION','ANNULATION_MISSION','CANDIDATURE','ASSIGNATION',
        'POINTAGE','SIGNATURE_CONTRAT','EVALUATION','PAIEMENT','FACTURATION',
        'DONNEES_PERSO_CONSULTATION','DONNEES_PERSO_EXPORT','DONNEES_PERSO_SUPPRESSION',
        'ADMIN_ACTION','SYSTEM','RIB_CONSULTE','RIB_PARTAGE','CONTRAT_SIGNE',
        'DOCUMENT_CONSULTATION','DOCUMENT_TELEVERSEMENT','DONNEES_PERSO_MODIFICATION',
        'EXPORT_RH_PAIE','FINANCE_FACTURE_PAYEE','MISSION_ASSIGNATION','MISSION_CREATION',
        'RGPD_EXPORT_DONNEES','DEGEL_APPLIED','OVERRIDE_CHAMP_POST_GEL','GEL_APPLIED',
        'OVERRIDE_ANTI_SEED','CONNECT_METADATA_MANQUANTE','DOCUMENT_VERIFICATION_AUTO',
        'FACTURE_COMMISSION_PAYEE_SKIP_ANOMALIE','FACTURE_HONORAIRES_PAYEE_SKIP_ANOMALIE',
        'FINANCE_CHARGE_EXPIRED','FINANCE_CHARGE_FAILED','FINANCE_CHARGE_PENDING',
        'FINANCE_CHARGE_REFUNDED','FINANCE_DISPUTE_CLOSE','FINANCE_DISPUTE_OUVERTE',
        'FINANCE_PAYOUT_CANCELED','FINANCE_PAYOUT_CREATED','FINANCE_PAYOUT_FAILED',
        'FINANCE_PAYOUT_PAID','FINANCE_SEPA_CAPTURE','FINANCE_TRANSFER_CONNECT',
        'FINANCE_TRANSFER_CREATED','FINANCE_TRANSFER_FAILED','FINANCE_TRANSFER_REVERSED',
        'FINANCE_TRANSFER_UPDATED','STRIPE_CHECKOUT_ORPHANED_RECOVERED',
        'STRIPE_CONNECT_ACCOUNT_DELETED','ATTESTATION_SANTE_SIGNEE','EXCLUSION_CREEE',
        'EXCLUSION_SUPPRIMEE','FACTURE_GENEREE','MISSION_ANNULATION_SERIE','MISSION_MODIFICATION',
        'PAIEMENT_SOIGNANT_DECLARE_ETAB','RECLAMATION_CREEE','ADMIN_CONSULTATION_ETABLISSEMENT',
        'ADMIN_CONSULTATION_SOIGNANT','DOCUMENT_SUPPRESSION','HEURES_EXTERNES_DECLAREES',
        'MISSION_ANNULATION','NOTE_HONORAIRES_GENEREE','PRESENCE_CONTESTATION',
        'PRESENCE_POINTAGE_ARRIVEE','PRESENCE_VALIDATION','PRESENCE_VALIDATION_LOT',
        'RGPD_CONSENTEMENT_DONNE','PAIEMENT_MONTANT_ECART',
        'FACTURE_COMMISSION_CREATED_VIA_STRIPE'
    ])
);
