-- READ ONLY. Metadata only: no business rows, passwords, Vault contents or job commands.
-- Future official schema-only dump, not this JSON, is the import source.
WITH ns AS (SELECT oid,nspname,nspowner,nspacl FROM pg_namespace WHERE nspname IN ('public','private','auth','storage')),
managed AS (SELECT c.* FROM pg_class c JOIN ns ON ns.oid=c.relnamespace WHERE ns.nspname IN ('auth','storage'))
SELECT jsonb_build_object(
 'observed_at',clock_timestamp(), 'postgres_version',current_setting('server_version'),
 'extensions',(SELECT jsonb_agg(jsonb_build_object('name',e.extname,'version',e.extversion,'schema',n.nspname) ORDER BY e.extname) FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace),
 'schemas',(SELECT jsonb_agg(jsonb_build_object('schema',nspname,'owner',pg_get_userbyid(nspowner),'acl',nspacl::text) ORDER BY nspname) FROM ns),
 'roles',(SELECT jsonb_agg(jsonb_build_object('name',rolname,'superuser',rolsuper,'inherit',rolinherit,'login',rolcanlogin,'bypassrls',rolbypassrls) ORDER BY rolname) FROM pg_roles WHERE rolname IN ('postgres','anon','authenticated','service_role','authenticator','supabase_admin','supabase_auth_admin','supabase_storage_admin','supabase_functions_admin')),
 'memberships',(SELECT jsonb_agg(jsonb_build_object('role',r.rolname,'member',m.rolname,'admin_option',am.admin_option) ORDER BY r.rolname,m.rolname) FROM pg_auth_members am JOIN pg_roles r ON r.oid=am.roleid JOIN pg_roles m ON m.oid=am.member WHERE r.rolname IN ('postgres','anon','authenticated','service_role','authenticator','supabase_admin','supabase_auth_admin','supabase_storage_admin','supabase_functions_admin') OR m.rolname IN ('postgres','anon','authenticated','service_role','authenticator','supabase_admin','supabase_auth_admin','supabase_storage_admin','supabase_functions_admin')),
 'private_routines',(SELECT jsonb_agg(jsonb_build_object('identity',p.oid::regprocedure::text,'kind',p.prokind,'owner',pg_get_userbyid(p.proowner),'acl',p.proacl::text,'security_definer',p.prosecdef,'definition_md5',md5(pg_get_functiondef(p.oid))) ORDER BY p.oid::regprocedure::text) FROM pg_proc p JOIN ns ON ns.oid=p.pronamespace WHERE ns.nspname='private' AND p.prokind IN ('f','p')),
 'private_relations',(SELECT jsonb_agg(jsonb_build_object('name',c.relname,'kind',c.relkind,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity) ORDER BY c.relname) FROM pg_class c JOIN ns ON ns.oid=c.relnamespace WHERE ns.nspname='private' AND c.relkind IN ('r','p','v','m','S')),
 'private_columns',(SELECT jsonb_agg(jsonb_build_object('table',c.relname,'column',a.attname,'type',format_type(a.atttypid,a.atttypmod),'not_null',a.attnotnull,'identity',a.attidentity,'generated',a.attgenerated,'default_md5',md5(pg_get_expr(d.adbin,d.adrelid))) ORDER BY c.relname,a.attnum) FROM pg_class c JOIN ns ON ns.oid=c.relnamespace JOIN pg_attribute a ON a.attrelid=c.oid LEFT JOIN pg_attrdef d ON d.adrelid=c.oid AND d.adnum=a.attnum WHERE ns.nspname='private' AND a.attnum>0 AND NOT a.attisdropped),
 'private_constraints',(SELECT jsonb_agg(jsonb_build_object('table',c.conrelid::regclass::text,'name',c.conname,'type',c.contype,'definition',pg_get_constraintdef(c.oid,true)) ORDER BY c.conrelid::regclass::text,c.conname) FROM pg_constraint c JOIN ns ON ns.oid=c.connamespace WHERE ns.nspname='private'),
 'custom_managed_triggers',(SELECT jsonb_agg(jsonb_build_object('table',t.tgrelid::regclass::text,'name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid,true),'function',t.tgfoid::regprocedure::text,'function_md5',md5(pg_get_functiondef(t.tgfoid))) ORDER BY t.tgrelid::regclass::text,t.tgname) FROM pg_trigger t JOIN managed c ON c.oid=t.tgrelid WHERE NOT t.tgisinternal),
 'managed_policies',(SELECT jsonb_agg(jsonb_build_object('table',p.polrelid::regclass::text,'name',p.polname,'command',p.polcmd,'permissive',p.polpermissive,'roles',(SELECT jsonb_agg(CASE WHEN r=0 THEN 'PUBLIC' ELSE pg_get_userbyid(r) END) FROM unnest(p.polroles) r),'using',pg_get_expr(p.polqual,p.polrelid),'check',pg_get_expr(p.polwithcheck,p.polrelid)) ORDER BY p.polrelid::regclass::text,p.polname) FROM pg_policy p JOIN managed c ON c.oid=p.polrelid),
 'managed_acl',(SELECT jsonb_agg(jsonb_build_object('table',c.oid::regclass::text,'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity) ORDER BY c.oid::regclass::text) FROM managed c WHERE c.relname IN ('users','sessions','objects','buckets')),
 'registry_exists',to_regclass('supabase_migrations.schema_migrations') IS NOT NULL,
 'security_inventory_exists',to_regclass('private.security_definer_inventory') IS NOT NULL
) AS catalogue;
