import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {NAMES,projectExtensions,compareRequired} from './extensions.mjs';
const source=JSON.parse(readFileSync(new URL('../export/scope.json',import.meta.url))).extensions;
const runtime=()=>({postgres_major:17,extensions:source.map(e=>({name:e.name,installed:{version:e.version,schema:e.schema},available_count:1,available_truncated:false,available_versions:[{version:e.version,superuser:true,trusted:false,relocatable:false,schema:e.schema,requires:null}]}))});
test('available does not mean installed, and compatibility never claims an import',()=>{const r=runtime();r.extensions.find(e=>e.name==='pgjwt').installed=null;const d=compareRequired(source,r);assert.equal(d.declarations_compatible,true);assert.equal(d.import_ready,false);assert.equal(d.checks.find(e=>e.name==='pgjwt').installed_version_matches,null)});
test('missing pgjwt is preserved as a blocker, never silently omitted',()=>{const r=runtime(),j=r.extensions.find(e=>e.name==='pgjwt');j.installed=null;j.available_versions=[];j.available_count=0;const d=compareRequired(source,r);assert.equal(d.declarations_compatible,false);assert.equal(d.checks.length,9);assert.equal(d.checks.find(e=>e.name==='pgjwt').exact_version_available,false)});
test('installed mismatches or truncated catalogue are not treated as compatible',()=>{const r=runtime();r.extensions[0].installed.version='9.9';assert.equal(compareRequired(source,r).declarations_compatible,false);const x=runtime();x.extensions[0].installed.schema='public';assert.equal(compareRequired(source,x).declarations_compatible,false)});
test('unexpected names, duplicates, malformed versions or unsafe fields refuse',()=>{
 for(const mutate of [r=>r.postgres_major=16,r=>r.extensions.pop(),r=>r.extensions[0].name='CANARY_SECRET',r=>r.extensions[0].name=r.extensions[1].name,r=>r.extensions[0].installed.version='https://CANARY_SECRET',r=>r.extensions[0].available_count=2]){const r=runtime();mutate(r);assert.throws(()=>projectExtensions(r),/^Error: EXTENSION_CATALOGUE_REFUSED$/)}
 const r=runtime();r.secret='CANARY_SECRET';r.extensions[0].available_versions[0].comment='CANARY_SECRET';assert.ok(!JSON.stringify(projectExtensions(r)).includes('CANARY'));assert.equal(NAMES.length,9);
});
