import { test, expect } from '@playwright/test';
import { simulerEtablissement, entrer, allerA, preuve, stabiliserLectures } from './helpers/recette-complete-etablissement';

test('alertes établissement : capacité, dix critères, panne, sauvegarde et contrôle central', async ({ page }, info) => {
 const { etat } = await simulerEtablissement(page);
 await page.route('**/rest/v1/rpc/fn_param_bool',async route=>{
  const req=route.request();
  if(!['127.0.0.1','localhost'].includes(new URL(req.url()).hostname)||req.method()!=='POST'||req.postDataJSON().p_cle!=='api_alertes_recherches_v1')return route.fallback();
  return route.fulfill({json:true});
 });
 etat.overrides.set('fn_capacite_alertes_recherches', true);
 await entrer(page, 'connexion');
 etat.pannes.add('fn_lister_mes_filtres_sauvegardes');
 await allerA(page, '/etablissement/soignants');
 await expect(page.getByRole('alert').filter({hasText:'Vos recherches sauvegardées'})).toBeVisible();
 etat.pannes.delete('fn_lister_mes_filtres_sauvegardes');
 await page.getByRole('button',{name:'Réessayer',exact:true}).click();
 await expect(page.getByRole('alert').filter({hasText:'Vos recherches sauvegardées'})).toHaveCount(0);
 await expect(page.getByText('Aucun soignant ne correspond à vos critères.', { exact: true })).toBeVisible();
 if (!await page.getByLabel('Profession', { exact: true }).isVisible()) await page.getByRole('button', { name: 'Filtres', exact: true }).click();
 await page.getByLabel('Profession', { exact: true }).selectOption('IDE');
 await page.getByLabel("Type d'exercice", { exact: true }).selectOption('SALARIE');
 for (const [label, valeur] of [['Ville','Paris'],['Recherche libre','gériatrie'],['Distance max (km)','30'],['Note ≥','4.5'],['Score ≥','80'],['Expérience min (années)','3']]) await page.getByLabel(label, { exact: true }).fill(valeur);
 await page.getByRole('checkbox', { name: 'Disponible pour urgences' }).check();
 await page.getByRole('checkbox', { name: 'Documents complets', exact: true }).check();
 await stabiliserLectures(page);
 await page.getByRole('button', { name: 'Sauvegarder cette recherche', exact: true }).click();
 const dialog = page.getByRole('dialog');
 await dialog.getByLabel('Nom de la recherche', { exact: true }).fill('Alerte IDE Paris');
 await expect(dialog.getByRole('switch', { name: 'Recevoir des alertes email' })).toBeChecked();
 await dialog.getByRole('combobox').click();
 await page.getByRole('option', { name: 'Toutes les heures', exact: true }).click();
 await preuve(page, 'alerte-dix-criteres-frequence', info);
 etat.pannes.add('fn_creer_filtre_sauvegarde');
 await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click();
 await expect(page.getByText('Erreur enregistrement', { exact: true })).toBeVisible();
 await expect(dialog.getByLabel('Nom de la recherche', { exact: true })).toHaveValue('Alerte IDE Paris');
 expect(etat.operations.filter(o=>o.nom==='fn_creer_filtre_sauvegarde')).toHaveLength(0);
 etat.pannes.delete('fn_creer_filtre_sauvegarde');
 await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click();
 await expect(dialog).toHaveCount(0);
 const filtres = {profession:'IDE',type_exercice:'SALARIE',ville:'Paris',distance_max_km:'30',note_min:'4.5',score_min:'80',experience_min:'3',disponible_urgence:true,documents_valides:true,recherche_texte:'gériatrie'};
 expect(etat.operations.find(o=>o.nom==='fn_creer_filtre_sauvegarde')?.payload).toEqual({p_nom:'Alerte IDE Paris',p_audience:'ETAB_RECHERCHE_SOIGNANTS',p_filtres:filtres,p_alerte_active:true,p_frequence_alerte:'IMMEDIATE'});
 etat.pannes.add('fn_lister_mes_filtres_sauvegardes');
 await page.getByRole('button', { name: 'Recherches sauvegardées', exact: true }).click();
 await expect(page.getByRole('alert').filter({hasText:'Vos recherches sauvegardées'})).toBeVisible();
 await expect(page.getByText("Aucune recherche sauvegardée pour l'instant.",{exact:true})).toHaveCount(0);
 etat.pannes.delete('fn_lister_mes_filtres_sauvegardes');
 await page.getByRole('button',{name:'Réessayer',exact:true}).click();
 await expect(page.getByRole('heading', { name: 'Alerte IDE Paris', exact: true })).toBeVisible();
 await expect(page.getByText('Toutes les heures', { exact: false }).first()).toBeVisible();
 await page.getByRole('button', { name: 'Désactiver alertes', exact: true }).click();
 await expect(page.getByRole('button', { name: 'Activer alertes', exact: true })).toBeVisible();
 await page.getByRole('button', { name: 'Modifier', exact: true }).click();
 await dialog.getByRole('switch', { name: 'Alertes email', exact: true }).check();
 await dialog.getByRole('combobox').click();
 await page.getByRole('option', { name: 'Hebdomadaire', exact: true }).click();
 await dialog.getByRole('button', { name: 'Enregistrer', exact: true }).click();
 await expect(dialog).toHaveCount(0);
 expect(etat.operations.filter(o=>o.nom==='fn_modifier_filtre_sauvegarde').at(-1)?.payload).toEqual({p_id:'recherche-recette',p_nom:'Alerte IDE Paris',p_alerte_active:true,p_frequence_alerte:'HEBDOMADAIRE'});
 await preuve(page, 'alerte-gestion-centrale-active', info);
 await info.attach('alertes-actives-capture',{body:await page.screenshot({fullPage:true,animations:'disabled'}),contentType:'image/png'});
 // Le frontend peut précéder le déploiement SQL/Edge ou perdre sa capacité.
 etat.pannes.add('fn_capacite_alertes_recherches');
 await allerA(page, '/etablissement/parametres/recherches-sauvegardees');
 await expect(page.getByRole('alert').filter({hasText:'Le service d’alertes annoncé'})).toBeVisible();
 await page.getByRole('button', { name: 'Désactiver alertes', exact: true }).click();
 await expect(page.getByRole('button', { name: 'Activer alertes', exact: true })).toHaveCount(0);
 etat.pannes.delete('fn_capacite_alertes_recherches');
 await page.getByRole('button', { name: 'Vérifier à nouveau', exact: true }).click();
 await expect(page.getByRole('button', { name: 'Activer alertes', exact: true })).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1)).toBe(true);
 expect(etat.erreurs).toEqual([]);expect(etat.inconnues).toEqual([]);expect(etat.ecritures).toEqual([]);
});

test('ancien backend : sauvegarde sans alerte et aucun appel à une API absente',async({page},info)=>{
 const {etat}=await simulerEtablissement(page);
 const appelsCapacite:string[]=[];
 page.on('request',req=>{if(req.url().includes('/rpc/fn_capacite_alertes_recherches'))appelsCapacite.push(req.url());});
 await entrer(page,'connexion');await allerA(page,'/etablissement/soignants');
 await expect(page.getByText('La sauvegarde des filtres reste disponible.',{exact:false})).toBeVisible();
 await page.getByRole('button',{name:'Sauvegarder cette recherche',exact:true}).click();
 const dialogue=page.getByRole('dialog');
 await dialogue.getByLabel('Nom de la recherche',{exact:true}).fill('Sauvegarde sur ancien backend');
 await expect(dialogue.getByRole('switch')).toHaveCount(0);
 await dialogue.getByRole('button',{name:'Enregistrer',exact:true}).click();
 await expect(dialogue).toHaveCount(0);
 expect(etat.operations.find(o=>o.nom==='fn_creer_filtre_sauvegarde')?.payload.p_alerte_active).toBe(false);
 await page.getByRole('button',{name:'Recherches sauvegardées',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Sauvegarde sur ancien backend',exact:true})).toBeVisible();
 await expect(page.getByRole('button',{name:'Activer alertes',exact:true})).toHaveCount(0);
 expect(appelsCapacite).toEqual([]);
 await preuve(page,'alertes-ancien-backend-compatible',info);
 expect(etat.erreurs).toEqual([]);expect(etat.inconnues).toEqual([]);expect(etat.ecritures).toEqual([]);
});

test('alerte rapide soignant : sept critères réels, lecture en panne, nouvel essai et aucun doublon', async ({ page }, info) => {
 const { simulerSoignant, entrer: entrerSoignant, aller, preuve: preuveSoignant } = await import('./helpers/recette-complete-soignant');
 const state = await simulerSoignant(page);
 const criteres = {profession:'IDE',rayonKm:25,tauxMin:30,typeContrat:'CDD',urgentesOnly:true,horaire:'NUIT',villeRecherche:'Paris'};
 const recherches = [{id:'source',nom:'Critères précis de recette',audience:'SOIGNANT_RECHERCHE_MISSIONS',filtres:criteres,alerte_active:false,frequence_alerte:'QUOTIDIENNE',dernier_check_le:'2026-09-25T09:00:00Z',nb_resultats_dernier_check:0}];
 state.overrides.set('fn_lister_mes_filtres_sauvegardes', recherches);
 const creations:Record<string,unknown>[]=[];
 await page.route('**/rest/v1/rpc/fn_creer_filtre_sauvegarde', async route=>{
  const req=route.request();
  if(!['127.0.0.1','localhost'].includes(new URL(req.url()).hostname)||req.method()!=='POST')return route.fallback();
  const p=req.postDataJSON();creations.push(p);
  recherches.push({id:'alerte-creee',nom:p.p_nom,audience:p.p_audience,filtres:p.p_filtres,alerte_active:p.p_alerte_active,frequence_alerte:p.p_frequence_alerte,dernier_check_le:'2026-09-25T09:00:00Z',nb_resultats_dernier_check:0});
  return route.fulfill({json:{success:true,id:'alerte-creee'}});
 });
 await entrerSoignant(page,'connexion');await aller(page,'/soignant/parametres/recherches-sauvegardees');
 await page.getByRole('button',{name:'Aller à la recherche',exact:true}).click();
 const quiz=page.getByRole('dialog',{name:'5 questions pour un deck qui te ressemble'});
 await expect(quiz).toBeVisible();await quiz.getByRole('button',{name:'Plus tard',exact:true}).click();
 await page.getByRole('tab',{name:'Liste',exact:true}).click();
 await expect(page.getByRole('button',{name:'🌙 Nuit',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(page.getByRole('button',{name:'🔥 Urgentes',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(page.getByRole('heading',{name:'Aucune mission trouvée',exact:true})).toBeVisible();
 await expect(page.getByText('Crée une alerte : les nouvelles missions seront vérifiées toutes les heures. Tu recevras un email si elles correspondent à tes critères.',{exact:true})).toBeVisible();
 recherches.splice(0,1);
 const ouvrir=()=>page.getByRole('button',{name:'🔔 Me prévenir des prochaines missions',exact:true}).click();
 await ouvrir();
 const dialog=page.getByRole('dialog',{name:'🔔 Créer une alerte missions'});
 await expect(dialog).toContainText('toutes les heures');
 state.failures.add('fn_lister_mes_filtres_sauvegardes');
 await dialog.getByRole('button',{name:"Activer l'alerte",exact:true}).click();
 await expect(page.getByText('Impossible de vérifier vos alertes existantes. Réessayez.',{exact:true})).toBeVisible();
 expect(creations).toHaveLength(0);await expect(dialog).toBeVisible();
 state.failures.delete('fn_lister_mes_filtres_sauvegardes');
 await dialog.getByRole('button',{name:"Activer l'alerte",exact:true}).click();
 await expect(dialog).toHaveCount(0);
 expect(creations).toHaveLength(1);
 expect(creations[0]).toMatchObject({p_filtres:criteres,p_alerte_active:true,p_frequence_alerte:'IMMEDIATE',p_audience:'SOIGNANT_RECHERCHE_MISSIONS'});
 await ouvrir();await dialog.getByRole('button',{name:"Activer l'alerte",exact:true}).click();
 await expect(dialog).toHaveCount(0);expect(creations).toHaveLength(1);
 await preuveSoignant(page,'alerte-rapide-sept-criteres',info,true);
 expect(state.unknown).toEqual([]);expect(state.errors).toEqual([]);
});
