/**
 * submit-to-chorus — STUB (pending PISTE credentials)
 *
 * Sera activé quand les credentials PISTE seront disponibles.
 * En attendant : insère une ligne dans chorus_submissions avec
 * status='pending_credentials' et retourne 202 Accepted.
 *
 * CP-LITIGES-7a FIX 15 : support type_document AVOIR.
 * - Accepte type_document optionnel ('FACTURE' | 'AVOIR').
 * - Pour AVOIR : récupère chorus_avoir_reference_invoice depuis
 *   factures_honoraires et le stocke dans chorus_submissions.
 * - Prépare le payload pour l'API PISTE DeposerPDFacture
 *   (BT-3=381 + référence facture origine).
 *
 * Voir docs/invoicing.md > "Activation Chorus" pour les étapes.
 */

import { createClient } from 'npm:@supabase/supabase-js@2';

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response(null, { status: 204 });

  try {
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,
      { auth: { persistSession: false } },
    );

    const { facture_honoraire_id, type_document } = await req.json();
    if (!facture_honoraire_id) return json({ error: 'facture_honoraire_id requis' }, 400);

    const docType: 'FACTURE' | 'AVOIR' = type_document === 'AVOIR' ? 'AVOIR' : 'FACTURE';

    // For AVOIR: fetch the reference invoice number (required for Chorus Pro deposit)
    let avoirReferenceInvoice: string | null = null;
    if (docType === 'AVOIR') {
      const { data: fh } = await supabaseAdmin
        .from('factures_honoraires')
        .select('chorus_avoir_reference_invoice')
        .eq('id', facture_honoraire_id)
        .single();

      avoirReferenceInvoice = fh?.chorus_avoir_reference_invoice ?? null;
      if (!avoirReferenceInvoice) {
        console.warn(`[submit-to-chorus] AVOIR ${facture_honoraire_id} sans chorus_avoir_reference_invoice — soumission enregistrée mais incomplète`);
      }
    }

    // Check if PISTE credentials are configured
    const pisteClientId = Deno.env.get('PISTE_CLIENT_ID');
    const pisteClientSecret = Deno.env.get('PISTE_CLIENT_SECRET');

    if (!pisteClientId || !pisteClientSecret) {
      console.log(`[submit-to-chorus] PISTE credentials pending — ${docType} submission deferred (id=${facture_honoraire_id})`);

      const { data: submission, error } = await supabaseAdmin
        .from('chorus_submissions')
        .insert({
          invoice_id: facture_honoraire_id,
          submission_type: 'SAISIE_API',
          type_document: docType,
          avoir_reference_invoice: avoirReferenceInvoice,
          status: 'pending_credentials',
          error_message: 'PISTE credentials not yet configured — submission will be retried when credentials are available',
        })
        .select('id')
        .single();

      if (error) {
        console.error('Error creating chorus_submission:', error);
        return json({ error: error.message }, 500);
      }

      await supabaseAdmin
        .from('factures_honoraires')
        .update({
          chorus_submission_id: submission!.id,
          chorus_submission_status: 'pending_credentials',
        })
        .eq('id', facture_honoraire_id);

      return json({
        accepted: true,
        status: 'pending_credentials',
        submission_id: submission!.id,
        type_document: docType,
        message: `Soumission Chorus Pro (${docType}) différée — credentials PISTE en attente de configuration.`,
      }, 202);
    }

    // ═══ REAL PISTE SUBMISSION (activated when credentials exist) ═══
    // TODO: Implement real OAuth2 + DeposerPDFacture call
    //
    // For AVOIR (BT-3=381):
    //   - The Factur-X XML already contains BT-3=381 (generated by generate-invoice CP6).
    //   - chorus_avoir_reference_invoice holds the numero_facture of the original
    //     invoice already deposited on Chorus Pro — include as metadata.
    //   - The same PISTE endpoint (DeposerPDFacture) accepts both invoices and
    //     credit notes; the BT-3 value in the embedded XML distinguishes them.
    //   - If Chorus rejects with DUPLICATE_INVOICE, this is normal for retries.
    //
    // This will be filled in by scripts/activate-chorus.ts validation.

    console.log(`[submit-to-chorus] PISTE credentials found — real ${docType} submission not yet implemented (id=${facture_honoraire_id})`);

    const { data: submission } = await supabaseAdmin
      .from('chorus_submissions')
      .insert({
        invoice_id: facture_honoraire_id,
        submission_type: 'SAISIE_API',
        type_document: docType,
        avoir_reference_invoice: avoirReferenceInvoice,
        status: 'pending',
      })
      .select('id')
      .single();

    await supabaseAdmin
      .from('factures_honoraires')
      .update({
        chorus_submission_id: submission!.id,
        chorus_submission_status: 'pending',
      })
      .eq('id', facture_honoraire_id);

    return json({
      accepted: true,
      status: 'pending',
      submission_id: submission!.id,
      type_document: docType,
      message: `Soumission Chorus Pro (${docType}) enregistrée — traitement en cours.`,
    }, 202);

  } catch (err) {
    console.error('submit-to-chorus error:', err);
    return json({ error: err instanceof Error ? err.message : 'Erreur interne' }, 500);
  }
});
