-- Registre de l'application opérationnelle anticipée de la migration
-- 20260720172500_hygiene_sessions_playwright.sql via l'API Supabase.
-- Le DDL canonique reste dans le fichier d'origine ; ce jalon empêche tout
-- drift du registre sans rejouer une seconde fois le cron initial.
