-- J2.3.C — Filtres sauvegardés + alertes nouvelles missions/soignants
-- Sujet 1 : Schema DB

DO $$ BEGIN
  CREATE TYPE public.filtre_audience AS ENUM ('SOIGNANT_RECHERCHE_MISSIONS','ETAB_RECHERCHE_SOIGNANTS');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.filtre_frequence_alerte AS ENUM ('IMMEDIATE','QUOTIDIENNE','HEBDOMADAIRE');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Étendre l'enum type_evenement_notification : NOUVEAU_SOIGNANT_MATCHANT_FILTRE
-- ALTER TYPE ADD VALUE IF NOT EXISTS : non transactionnel, idempotent (PG 9.6+).
-- À sortir d'un DO block car ALTER TYPE … ADD ne peut pas s'exécuter à
-- l'intérieur d'une transaction commit-after-script.
ALTER TYPE public.type_evenement_notification ADD VALUE IF NOT EXISTS 'NOUVEAU_SOIGNANT_MATCHANT_FILTRE';

CREATE TABLE IF NOT EXISTS public.filtres_sauvegardes (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  utilisateur_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nom text NOT NULL CHECK (length(nom) BETWEEN 1 AND 100),
  audience public.filtre_audience NOT NULL,
  filtres jsonb NOT NULL DEFAULT '{}'::jsonb,
  alerte_active boolean NOT NULL DEFAULT false,
  frequence_alerte public.filtre_frequence_alerte NOT NULL DEFAULT 'QUOTIDIENNE',
  dernier_check_le timestamptz NOT NULL DEFAULT now(),
  nb_resultats_dernier_check integer NOT NULL DEFAULT 0,
  cree_le timestamptz NOT NULL DEFAULT now(),
  mis_a_jour_le timestamptz NOT NULL DEFAULT now(),
  UNIQUE (utilisateur_id, nom)
);

CREATE INDEX IF NOT EXISTS idx_filtres_sauvegardes_alerte_cron
  ON public.filtres_sauvegardes (alerte_active, frequence_alerte, dernier_check_le)
  WHERE alerte_active = true;

ALTER TABLE public.filtres_sauvegardes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS fs_select_own ON public.filtres_sauvegardes;
CREATE POLICY fs_select_own ON public.filtres_sauvegardes
  FOR SELECT TO authenticated USING (utilisateur_id = auth.uid() OR est_admin());
DROP POLICY IF EXISTS fs_insert_own ON public.filtres_sauvegardes;
CREATE POLICY fs_insert_own ON public.filtres_sauvegardes
  FOR INSERT TO authenticated WITH CHECK (utilisateur_id = auth.uid());
DROP POLICY IF EXISTS fs_update_own ON public.filtres_sauvegardes;
CREATE POLICY fs_update_own ON public.filtres_sauvegardes
  FOR UPDATE TO authenticated USING (utilisateur_id = auth.uid())
  WITH CHECK (utilisateur_id = auth.uid());
DROP POLICY IF EXISTS fs_delete_own ON public.filtres_sauvegardes;
CREATE POLICY fs_delete_own ON public.filtres_sauvegardes
  FOR DELETE TO authenticated USING (utilisateur_id = auth.uid());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.filtres_sauvegardes TO authenticated;
GRANT SELECT, INSERT, UPDATE ON public.filtres_sauvegardes TO service_role;

DROP TRIGGER IF EXISTS trg_fs_updated_at ON public.filtres_sauvegardes;
CREATE TRIGGER trg_fs_updated_at BEFORE UPDATE ON public.filtres_sauvegardes
  FOR EACH ROW EXECUTE FUNCTION public.fn_trg_pn_updated_at();

ALTER TABLE public.journaux_audit DROP CONSTRAINT IF EXISTS journaux_audit_action_check;
ALTER TABLE public.journaux_audit ADD CONSTRAINT journaux_audit_action_check CHECK (action IN (
  'INSCRIPTION','CONNEXION','DECONNEXION','MODIFICATION_PROFIL','SUPPRESSION_COMPTE',
  'UPLOAD_DOCUMENT','TELECHARGEMENT_DOCUMENT','VERIFICATION_DOCUMENT','VERIFICATION_RPPS',
  'CREATION_MISSION','MODIFICATION_MISSION','ANNULATION_MISSION','CANDIDATURE','ASSIGNATION',
  'POINTAGE','SIGNATURE_CONTRAT','EVALUATION','PAIEMENT','FACTURATION',
  'DONNEES_PERSO_CONSULTATION','DONNEES_PERSO_EXPORT','DONNEES_PERSO_SUPPRESSION',
  'ADMIN_ACTION','SYSTEM','RIB_CONSULTE','RIB_PARTAGE','CONTRAT_SIGNE',
  'DOCUMENT_CONSULTATION','DOCUMENT_TELEVERSEMENT','DONNEES_PERSO_MODIFICATION',
  'EXPORT_RH_PAIE','FINANCE_FACTURE_PAYEE','MISSION_ASSIGNATION','MISSION_CREATION',
  'RGPD_EXPORT_DONNEES','RGPD_SUPPRESSION_COMPTE','RGPD_SUPPRESSION_COMPTE_ETABLISSEMENT',
  'DEGEL_APPLIED','OVERRIDE_CHAMP_POST_GEL','GEL_APPLIED','OVERRIDE_ANTI_SEED',
  'CONNECT_METADATA_MANQUANTE','DOCUMENT_VERIFICATION_AUTO',
  'FACTURE_COMMISSION_PAYEE_SKIP_ANOMALIE','FACTURE_HONORAIRES_PAYEE_SKIP_ANOMALIE',
  'FINANCE_CHARGE_EXPIRED','FINANCE_CHARGE_FAILED','FINANCE_CHARGE_PENDING',
  'FINANCE_CHARGE_REFUNDED','FINANCE_DISPUTE_CLOSE','FINANCE_DISPUTE_OUVERTE',
  'FINANCE_PAYOUT_CANCELED','FINANCE_PAYOUT_CREATED','FINANCE_PAYOUT_FAILED',
  'FINANCE_PAYOUT_PAID','FINANCE_SEPA_CAPTURE','FINANCE_TRANSFER_CONNECT',
  'FINANCE_TRANSFER_CREATED','FINANCE_TRANSFER_FAILED','FINANCE_TRANSFER_REVERSED',
  'FINANCE_TRANSFER_UPDATED','STRIPE_CHECKOUT_ORPHANED_RECOVERED',
  'STRIPE_CONNECT_ACCOUNT_DELETED','ATTESTATION_SANTE_SIGNEE',
  'EXCLUSION_CREEE','EXCLUSION_SUPPRIMEE','FACTURE_GENEREE',
  'MISSION_ANNULATION_SERIE','MISSION_MODIFICATION','PAIEMENT_SOIGNANT_DECLARE_ETAB',
  'RECLAMATION_CREEE','ADMIN_CONSULTATION_ETABLISSEMENT','ADMIN_CONSULTATION_SOIGNANT',
  'DOCUMENT_SUPPRESSION','HEURES_EXTERNES_DECLAREES','MISSION_ANNULATION',
  'NOTE_HONORAIRES_GENEREE','PRESENCE_CONTESTATION','PRESENCE_POINTAGE_ARRIVEE',
  'PRESENCE_VALIDATION','PRESENCE_VALIDATION_LOT','RGPD_CONSENTEMENT_DONNE',
  'PAIEMENT_MONTANT_ECART','FACTURE_COMMISSION_CREATED_VIA_STRIPE',
  'TAUX_COMMISSION_MODIFIE','LITIGE_GEL_SCOPE_MODIFIE',
  'PREFERENCE_NOTIFICATION_MODIFIEE','NOTIFICATION_SKIPPED',
  'SERIE_EMAIL_ENVOYE','SERIE_EMAIL_SKIPPED',
  'FILTRE_CREE','FILTRE_MODIFIE','FILTRE_SUPPRIME',
  'ALERTE_ACTIVEE','ALERTE_DESACTIVEE','ALERTE_ENVOYEE'
));

NOTIFY pgrst, 'reload schema';
