-- Ajoute CANDIDATURE_RECUE et MATCHING_SUPER_LIKE au CHECK constraint de
-- notifications.type — requis par fn_enregistrer_swipe (candidature auto)
-- et par l'edge function notif-match (super-like).

ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check CHECK (type = ANY (ARRAY[
  'CANDIDATURE_ACCEPTEE','CANDIDATURE_REFUSEE','CANDIDATURE_PROPOSEE','CANDIDATURE_RECUE',
  'MISSION_ACCEPTEE','MISSION_ANNULEE','MISSION_TERMINEE','MISSION_URGENTE','MISSION_NON_POURVUE','MISSION_ASSIGNEE','MISSION_A_POURVOIR',
  'CONTRAT_A_SIGNER','CONTRAT_SIGNE',
  'FACTURE_EMISE','FACTURE_PAYEE',
  'DOCUMENT_EXPIRANT','RAPPEL_DOCUMENTS','DOCUMENT_VERIFIE','DOCUMENT_REJETE',
  'MESSAGE_RECU','MESSAGE_ADMIN',
  'POINTAGE_ARRIVEE','POINTAGE_DEPART',
  'EVALUATION_RECUE',
  'PARRAINAGE','CREDIT_PARRAINAGE','PARRAINAGE_PRIME_VERSEE',
  'RAPPEL_MISSION','RAPPEL_CANDIDATURES',
  'POOL_URGENCE','POOL_URGENCE_ACCEPTATION',
  'SYSTEM',
  'LITIGE_OUVERT','LITIGE_REPONSE','LITIGE_RESOLU','LITIGE_MEDIATION','LITIGE_RESOLU_AJUSTE','LITIGE_ESCALADE_ADMIN','LITIGE_MEDIATION_PRIORITAIRE','LITIGE_RAPPEL_J1','LITIGE_RAPPEL_J3','LITIGE_RAPPEL_J5',
  'CHORUS_DEPOSEE','CHORUS_MISE_A_DISPOSITION','CHORUS_PAIEMENT_EN_COURS','CHORUS_PAIEMENT_COMPTABILISE','CHORUS_REJETEE',
  'FAVORI_NOUVELLE_MISSION',
  'AVOIR_EMIS','COMMISSION_AJUSTEE',
  'REMBOURSEMENT_MANUEL_A_FAIRE','REMBOURSEMENT_CONFIRME',
  'MATCHING_SUPER_LIKE'
]));
