// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getSupabaseAuthStorage } from './auth-storage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL
  || "https://flripxtsyegjshnhzjkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
  || "sb_publishable_wrR-KGZqiovTPBym6mjXPw_V8l4ae-C";

export { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getSupabaseAuthStorage(),
    persistSession: true,
    autoRefreshToken: true,
    // La page de récupération valide elle-même les trois formats de callback
    // (implicit, PKCE, token_hash). La laisser aussi au SDK créerait une course
    // où le code peut être consommé deux fois ou confondu avec une session
    // ordinaire déjà présente dans le navigateur.
    detectSessionInUrl:
      typeof window === 'undefined' || window.location.pathname !== '/reset-password',
  }
});
