/**
 * Routes mobiles visibles par rôle.
 *
 * Source unique partagée par l'audit des comptes de recette stables et par
 * l'audit post-inscription de comptes entièrement neufs. Une nouvelle route
 * métier ne doit ainsi jamais être ajoutée à un seul des deux parcours.
 */
export const ROUTES_SOIGNANT = [
  '/soignant/tableau-de-bord',
  '/soignant/recherche-missions',
  '/soignant/missions',
  '/soignant/missions?tab=candidatures',
  '/soignant/missions?tab=passees',
  '/soignant/mes-gains',
  '/soignant/mes-gains?tab=factures',
  '/soignant/mes-gains?tab=bulletins',
  '/soignant/mes-gains?tab=avances',
  '/soignant/mandat-facturation',
  '/soignant/messagerie',
  '/soignant/mes-documents',
  '/soignant/presences',
  '/soignant/presences?tab=encours',
  '/soignant/presences?tab=aujourdhui',
  '/soignant/presences?tab=historique',
  '/soignant/score',
  '/soignant/evaluations',
  '/soignant/disponibilites',
  '/soignant/conformite',
  '/soignant/prevoyance',
  '/soignant/attestation-heures',
  '/soignant/passer-en-liberal',
  '/soignant/exclusions',
  '/soignant/charges',
  '/soignant/notifications',
  '/soignant/parrainage',
  '/soignant/litiges',
  '/soignant/litiges?tab=reclamations',
  '/soignant/premium',
  '/soignant/stripe-connect',
  '/soignant/classement',
  '/soignant/pool-urgence',
  '/soignant/mes-favoris',
  '/soignant/parametres/notifications',
  '/soignant/parametres/recherches-sauvegardees',
  '/soignant/profil',
  '/soignant/profil?tab=preferences',
  '/soignant/profil?tab=confidentialite',
  '/soignant/mon-compte',
] as const;

export const ROUTES_ETABLISSEMENT = [
  '/etablissement/tableau-de-bord',
  '/etablissement/missions',
  '/etablissement/missions/creer',
  '/etablissement/messagerie',
  '/etablissement/presences',
  '/etablissement/presences?tab=en_cours',
  '/etablissement/presences?tab=validees',
  '/etablissement/presences?tab=alertes',
  '/etablissement/contrats',
  '/etablissement/facturation',
  '/etablissement/facturation?tab=attente',
  '/etablissement/facturation?tab=commissions',
  '/etablissement/facturation?tab=historique',
  '/etablissement/facturation?tab=exports',
  '/etablissement/soignants',
  '/etablissement/mes-favoris',
  '/etablissement/pool-urgence',
  '/etablissement/equipe',
  '/etablissement/rh',
  '/etablissement/rh?tab=analytics',
  '/etablissement/export-paie',
  '/etablissement/score',
  '/etablissement/evaluations-a-faire',
  '/etablissement/litiges',
  '/etablissement/litiges?tab=reclamations',
  '/etablissement/notifications',
  '/etablissement/parrainage',
  '/etablissement/parametres/notifications',
  '/etablissement/parametres/recherches-sauvegardees',
  '/etablissement/parametres',
  '/etablissement/parametres?tab=facturation',
  '/etablissement/parametres?tab=operations',
  '/etablissement/parametres?tab=notifications',
  '/etablissement/parametres?tab=securite',
  '/etablissement/mon-compte',
  '/etablissement/activer',
  '/etablissement/premium',
  '/etablissement/chorus-config',
  '/etablissement/mes-reclamations',
] as const;
